Repository team-mohaeng/mohaeng-iOS, pull requests merged in 2021-12, with the labels that each got.

#615 [#614] 커뮤니티 페이징
  Mohaeng/Mohaeng.xcodeproj/project.pbxproj
  Mohaeng/Mohaeng/Resources/Storyboards/Feed/Feed.storyboard
  Mohaeng/Mohaeng/Resources/Storyboards/Feed/FeedDetail.storyboard
  Mohaeng/Mohaeng/Sources/APIModels/Feed.swift
  Mohaeng/Mohaeng/Sources/APIServices/FeedAPI/FeedAPI.swift
  Mohaeng/Mohaeng/Sources/APIServices/FeedAPI/FeedService.swift
  Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/FeedDetailCollectionViewCell.swift
  Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/PlusButtonCollectionViewCell.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedDetailViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/MyDrawerViewController.swift
Labels: feat 🌹, yezi✨

#618 [#616] crash 대응
  Mohaeng/Mohaeng.xcodeproj/project.pbxproj
  Mohaeng/Mohaeng/Resources/Info.plist
  Mohaeng/Mohaeng/Resources/Lottie/loading.json
  Mohaeng/Podfile
  Mohaeng/Podfile.lock
Labels: feat 🌹, choyi 🎱

#620 [#619] 피드 커뮤니티 페이징 버그 수정
  Mohaeng/Mohaeng/Resources/Storyboards/Feed/Feed.storyboard
  Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/FeedDetailCollectionViewCell.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedDetailViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedViewController.swift
Labels: fix 🚨, yezi✨

#621 [#617] 로그아웃, 회원탈퇴 시 푸쉬알림은 계속 오는 현상 수정
  Mohaeng/Mohaeng.xcodeproj/project.pbxproj
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/EmailLoginViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/LoginViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpThirdViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/Setting/SettingViewController.swift
Labels: fix 🚨, choyi 🎱

#623 [#235] 로그인 실패 시 에러 팝업 띄우기
  Mohaeng/Mohaeng/Resources/Constants/String.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/LoginViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpFirstViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpThirdViewController.swift
Labels: fix 🚨, choyi 🎱

#624 [#622] 토큰이 만료되었을 때 메인 뷰가 뜨는 에러
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/HomeViewController.swift
Labels: fix 🚨, choyi 🎱

#627 [#625] 이메일로 로그인 밑줄 수정
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/EmailLogin.storyboard
Labels: fix 🚨, seungchan🗻

#628 [#626] 글쓰기뷰 글자수 제한 수정, 피드 뷰 로티 hidden 값 수정
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/WritingViewController.swift
Labels: fix 🚨, refactor 🥲, yezi✨, yoonseo 🥑

#630 [#629] 닉네임 저장
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpThirdViewController.swift
Labels: fix 🚨, yoonseo 🥑

#636 [#635] Writing VC 네비바 색상 설정, 줄수 제한 PopUp 삭제
  Mohaeng/Mohaeng.xcodeproj/project.pbxproj
  Mohaeng/Mohaeng/Sources/Extensions/UINavigationController+Extension.swift
  Mohaeng/Mohaeng/Sources/Extensions/UITextView+Extension.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/WritingViewController.swift
Labels: fix 🚨, yoonseo 🥑

#637 [#NON_ISSUE] 카카오톡 앱 없을 때 카카오톡 계정으로 로그인
  Mohaeng/Mohaeng.xcodeproj/project.pbxproj
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/LoginViewController.swift
Labels: fix 🚨, choyi 🎱
