Repository team-mohaeng/mohaeng-iOS, pull requests merged in 2021-07, with the labels that each got.

#17 [#12] Course 뷰 로직
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Storyboards/Challenge/Course.storyboard
  Journey/Journey/Sources/APIModels/Challenge.swift
  Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.swift
  Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.xib
  Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.swift
  Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.xib
  Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.swift
  Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.xib
  Journey/Journey/Sources/Extensions/UIColor+Extension.swift
  Journey/Journey/Sources/ViewControllers/Challenge/CourseViewController.swift
Labels: choyi 🎱, feat 🌹

#19 [#18] 코스 라이브러리 뷰
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Colors.xcassets/doneCourseBg.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/doneCourseButton.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/undoneCourseBg.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/undoneCourseButton.colorset/Contents.json
  Journey/Journey/Resources/Constants/Storyboard.swift
  Journey/Journey/Resources/Constants/ViewController.swift
  Journey/Journey/Resources/Constants/Xib.swift
  Journey/Journey/Resources/Storyboards/Challenge/CourseLibrary.storyboard
  Journey/Journey/Sources/AppModels/Course.swift
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.swift
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.xib
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.swift
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.xib
  Journey/Journey/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
Labels: choyi 🎱, feat 🌹

#21 [#20] 로그인 flow
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Constants/Storyboard.swift
  Journey/Journey/Resources/Constants/ViewController.swift
  Journey/Journey/Resources/Storyboards/Auth/Login.storyboard
  Journey/Journey/Sources/SceneDelegate.swift
  Journey/Journey/Sources/ViewControllers/Auth/LoginViewController.swift
Labels: choyi 🎱, feat 🌹

#22 [#13] 메인뷰 UI
  Journey/Journey/Resources/Assets.xcassets/awardIcon.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/awardIcon.imageset/awardIcon-1.png
  Journey/Journey/Resources/Assets.xcassets/awardIcon.imageset/awardIcon-2.png
  Journey/Journey/Resources/Assets.xcassets/awardIcon.imageset/awardIcon.png
  Journey/Journey/Resources/Assets.xcassets/journeyMainSampleImg.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/journeyMainSampleImg.imageset/journeyMainSampleImg-1.png
  Journey/Journey/Resources/Assets.xcassets/journeyMainSampleImg.imageset/journeyMainSampleImg-2.png
  Journey/Journey/Resources/Assets.xcassets/journeyMainSampleImg.imageset/journeyMainSampleImg.png
  Journey/Journey/Resources/Assets.xcassets/messageIcon.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/messageIcon.imageset/messageIcon-1.png
  Journey/Journey/Resources/Assets.xcassets/messageIcon.imageset/messageIcon-2.png
  Journey/Journey/Resources/Assets.xcassets/messageIcon.imageset/messageIcon.png
  Journey/Journey/Resources/Assets.xcassets/settingsIcon.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/settingsIcon.imageset/settingIcon-1.png
  Journey/Journey/Resources/Assets.xcassets/settingsIcon.imageset/settingIcon-2.png
  Journey/Journey/Resources/Assets.xcassets/settingsIcon.imageset/settingIcon.png
  Journey/Journey/Resources/Colors.xcassets/beige.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/darkGray.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/hotPink.colorset/Contents.json
  Journey/Journey/Resources/Storyboards/Home/Home.storyboard
  Journey/Journey/Sources/ViewControllers/Home/HomeViewController.swift
Labels: feat 🌹, yezi💩

#26 [#25] push notification 환경설정
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Journey.entitlements
  Journey/Journey/Resources/GoogleService-Info.plist
  Journey/Journey/Resources/Info.plist
  Journey/Journey/Sources/APIModels/Course.swift
  Journey/Journey/Sources/AppDelegate.swift
  Journey/Journey/Sources/AppModels/Course.swift
  Journey/Podfile
  Journey/Podfile.lock
Labels: choyi 🎱, feat 🌹

#27 [#23] 소확행 구경하기뷰 UI
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Storyboards/Feed/Feed.storyboard
  Journey/Journey/Sources/Cells/FeedCollectionView/FeedContentsCollectionViewCell.swift
  Journey/Journey/Sources/Cells/FeedCollectionView/FeedContentsCollectionViewCell.xib
  Journey/Journey/Sources/Extensions/UIColor+Extension.swift
  Journey/Journey/Sources/SceneDelegate.swift
  Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
  Journey/Journey/Sources/Views/FeedHeaderView.swift
  Journey/Journey/Sources/Views/FeedHeaderView.xib
Labels: feat 🌹, yezi✨

#30 [#NON_ISSUE] 파일 경로 수정
  Journey/Journey.xcodeproj/project.pbxproj
Labels: chore 🛠, choyi 🎱

#40 [#37] URL Constant 추가하기
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Constants/URL.swift
Labels: choyi 🎱, docs 📃

#31 [#24] CourseLibrary 뷰 MVVM 패턴으로 migration하기
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.swift
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.swift
  Journey/Journey/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
  Journey/Journey/Sources/ViewModels/CourseListViewModel.swift
Labels: choyi 🎱, feat 🌹

#32 [#28] 소확행 자세히 보기 뷰
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Assets.xcassets/sampleHappinessImg.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/sampleHappinessImg.imageset/sampleHappinessImg.jpg
  Journey/Journey/Resources/Colors.xcassets/hashtagPink.colorset/Contents.json
  Journey/Journey/Resources/Constants/Storyboard.swift
  Journey/Journey/Resources/Constants/ViewController.swift
  Journey/Journey/Resources/Storyboards/Feed/Feed.storyboard
  Journey/Journey/Resources/Storyboards/Feed/FeedDetail.storyboard
  Journey/Journey/Sources/ViewControllers/Feed/FeedDetailViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
Labels: feat 🌹, yezi✨

#36 [#15] Course cell들 CGPoint 다듬기
  Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.swift
  Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.xib
  Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.swift
  Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.xib
  Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.swift
  Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.xib
  Journey/Journey/Sources/ViewControllers/Challenge/CourseViewController.swift
Labels: choyi 🎱, refactor 🥲

#39 [#38] README 수정
  README.md
Labels: choyi 🎱, docs 📃

#43 [#42] Medal 뷰 짜기
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Assets.xcassets/flwGraphic.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/flwGraphic.imageset/flwGraphic.png
  Journey/Journey/Resources/Assets.xcassets/flwGraphic.imageset/flwGraphic@2x.png
  Journey/Journey/Resources/Assets.xcassets/flwGraphic.imageset/flwGraphic@3x.png
  Journey/Journey/Resources/Constants/Storyboard.swift
  Journey/Journey/Resources/Constants/ViewController.swift
  Journey/Journey/Resources/Constants/Xib.swift
  Journey/Journey/Resources/Storyboards/Home/Medal.storyboard
  Journey/Journey/Sources/Cells/MedalCollectionView/MedalCollectionViewCell.swift
  Journey/Journey/Sources/Cells/MedalCollectionView/MedalCollectionViewCell.xib
  Journey/Journey/Sources/ViewControllers/Home/MedalViewController.swift
  Journey/Journey/Sources/Views/MedalCollectionReusableView.swift
  Journey/Journey/Sources/Views/MedalCollectionReusableView.xib
  Journey/Journey/Sources/Views/ViewExmaple.swift
Labels: choyi 🎱, feat 🌹

#45 [#44] 커스텀 팝업 뷰 짜기
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.xib
  Journey/Journey/Sources/ViewControllers/PopUpViewController.xib
Labels: choyi 🎱, feat 🌹

#46 [#33] 내 서랍장 뷰 완성
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Constants/Storyboard.swift
  Journey/Journey/Resources/Constants/ViewController.swift
  Journey/Journey/Resources/Constants/Xib.swift
  Journey/Journey/Resources/Storyboards/Feed/MyDrawer.storyboard
  Journey/Journey/Sources/APIModels/AppDate.swift
  Journey/Journey/Sources/Extensions/ModalPresentationController.swift
  Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/MyDrawerViewController.swift
  Journey/Journey/Sources/Views/DatePickerViewController.swift
  Journey/Journey/Sources/Views/DatePickerViewController.xib
  Journey/Journey/Sources/Views/FeedHeaderView.swift
  Journey/Journey/Sources/Views/FeedHeaderView.xib
  Journey/Journey/Sources/Views/MyDrawerCollectionReusableView.swift
  Journey/Journey/Sources/Views/MyDrawerCollectionReusableView.xib
Labels: feat 🌹, yezi✨

#47 [#34] Model 추가하기
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Sources/APIModels/APIModelsExmaple.swift
  Journey/Journey/Sources/APIModels/Challenge.swift
  Journey/Journey/Sources/APIModels/Course.swift
  Journey/Journey/Sources/APIModels/Home.swift
  Journey/Journey/Sources/APIModels/User.swift
Labels: chore 🛠, choyi 🎱

#50 [#48] Model에 맞게 더미데이터 수정
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.swift
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.swift
  Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.swift
  Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.swift
  Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.swift
  Journey/Journey/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
  Journey/Journey/Sources/ViewControllers/Challenge/CourseViewController.swift
Labels: chore 🛠, choyi 🎱

#51 [#48] Medal 뷰 트랜지션 연결
  Journey/Journey/Resources/Storyboards/Home/Home.storyboard
  Journey/Journey/Resources/Storyboards/Home/Medal.storyboard
  Journey/Journey/Sources/ViewControllers/Home/HomeViewController.swift
Labels: choyi 🎱, feat 🌹

#56 [#53] 로그인뷰 짜기
  Journey/Journey/Resources/Storyboards/Auth/Login.storyboard
  Journey/Journey/Sources/ViewControllers/Auth/LoginViewController.swift
Labels: feat 🌹, seungchan🗻

#60 [#58] 소확행 작성하기 기분선택 뷰
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Assets.xcassets/circleGray.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/circleGray.imageset/circleGray.png
  Journey/Journey/Resources/Assets.xcassets/circlePink.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/circlePink.imageset/circlePink.png
  Journey/Journey/Resources/Assets.xcassets/sampleMoodImg.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/sampleMoodImg.imageset/sampleMoodImg.png
  Journey/Journey/Resources/Assets.xcassets/sampleMoodUnselectedImg.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/sampleMoodUnselectedImg.imageset/Mask Group.png
  Journey/Journey/Resources/Constants/Storyboard.swift
  Journey/Journey/Resources/Constants/ViewController.swift
  Journey/Journey/Resources/Storyboards/Feed/Mood.storyboard
  Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/MoodViewController.swift
  Journey/Journey/Sources/Views/FeedHeaderView.swift
  Journey/Journey/Sources/Views/FeedHeaderView.xib
Labels: feat 🌹, yezi✨

#63 [#57] SignUpFirst 뷰 component 배치
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Assets.xcassets/indicator.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/indicator.imageset/indicator.png
  Journey/Journey/Resources/Assets.xcassets/indicator.imageset/indicator@2x.png
  Journey/Journey/Resources/Assets.xcassets/indicator.imageset/indicator@3x.png
  Journey/Journey/Resources/Constants/Storyboard.swift
  Journey/Journey/Resources/Constants/ViewController.swift
  Journey/Journey/Resources/Storyboards/Auth/SignUpFirst.storyboard
  Journey/Journey/Sources/ViewControllers/Auth/SignUpFirstViewController.swift
Labels: feat 🌹, seungchan🗻

#67 [#66] 로그인, 회원가입 flow navigation bar init functions
  Journey/Journey/Resources/Storyboards/Auth/Login.storyboard
  Journey/Journey/Sources/ViewControllers/Auth/LoginViewController.swift
  Journey/Journey/Sources/ViewControllers/Auth/SignUpFirstViewController.swift
Labels: choyi 🎱, feat 🌹

#68 [#41] URL Constant 정리하기
  Journey/Journey/Resources/Constants/URL.swift
Labels: choyi 🎱, docs 📃

#74 [#62] 서버 통신 전 환경설정
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Constants/URL.swift
  Journey/Journey/Resources/Info.plist
  Journey/Journey/Sources/APIServices/NetworkResult.swift
Labels: chore 🛠, choyi 🎱

#73 [#69] Course 뷰 통신 연결
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Storyboards/Challenge/Course.storyboard
  Journey/Journey/Sources/APIModels/Course.swift
  Journey/Journey/Sources/APIServices/APIServicesExmaple.swift
  Journey/Journey/Sources/APIServices/CourseAPI/ChallengeAPI.swift
  Journey/Journey/Sources/APIServices/CourseAPI/ChallengeService.swift
  Journey/Journey/Sources/ViewControllers/Challenge/CourseViewController.swift
Labels: choyi 🎱, feat 🌹

#80 [#78] Tab bar design
  Journey/Journey/Resources/Colors.xcassets/tabbarBorderGray.colorset/Contents.json
  Journey/Journey/Sources/Extensions/UIColor+Extension.swift
  Journey/Journey/Sources/Extensions/UIView+Extension.swift
  Journey/Journey/Sources/ViewControllers/TabbarViewController.swift
Labels: choyi 🎱, feat 🌹

#85 [#71] 기분선택 - 글작성 트랜지션 연결
  Journey/Journey/Resources/Storyboards/Feed/Mood.storyboard
  Journey/Journey/Sources/ViewControllers/Feed/MoodViewController.swift
Labels: feat 🌹, yezi✨

#86 [#82] 해시태그 로직 추가
  Journey/Journey/Resources/Storyboards/Feed/Writing.storyboard
  Journey/Journey/Sources/Cells/FeedView/HashTagCollectionViewCell.swift
  Journey/Journey/Sources/Cells/FeedView/HashTagCollectionViewCell.xib
  Journey/Journey/Sources/ViewControllers/Feed/WritingViewController.swift
Labels: feat 🌹, yezi✨

#84 [#79] Color System 정리
  Journey/Journey/Resources/Colors.xcassets/Black1.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Black1Text.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Black2.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Black2Text.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Black3Text.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Green.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Grey1Bg.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Grey1Line.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Grey1Tab.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Grey2Bg.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Grey2Line.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Grey2Tab.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/GreyBtnInactive.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Icon.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Pink2.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Pink3.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/PinkMood.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Red.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/black4Text.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/pink1.colorset/Contents.json
  Journey/Journey/Sources/Extensions/UIColor+Extension.swift
Labels: choyi 🎱, docs 📃

#89 [#87] 커스텀 팝업 띄울 때 탭바가 위로 올라오는 현상 해결
  Journey/Journey/Sources/ViewControllers/Feed/WritingViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.xib
Labels: choyi 🎱, fix 🚨

#92 [#90] Pop Up view Action delegate
  Journey/Journey/Sources/ViewControllers/Feed/WritingViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.xib
Labels: choyi 🎱, feat 🌹

#93 [#91] IQKeyboardManager 옵션 추가
  Journey/Journey/Sources/AppDelegate.swift
Labels: chore 🛠, choyi 🎱

#95 [#76] Course 뷰 서버 수정사항 반영
  Journey/Journey/Sources/APIModels/Challenge.swift
  Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.swift
  Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.swift
  Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.swift
  Journey/Journey/Sources/ViewControllers/Challenge/CourseViewController.swift
Labels: choyi 🎱, feat 🌹

#99 [#96] 비밀번호 찾기 뷰 짜기
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Constants/Storyboard.swift
  Journey/Journey/Resources/Constants/ViewController.swift
  Journey/Journey/Resources/Storyboards/Auth/FindPassword.storyboard
  Journey/Journey/Sources/ViewControllers/Auth/FindPasswordViewController.swift
  Journey/Journey/Sources/ViewControllers/Auth/LoginViewController.swift
Labels: choyi 🎱, feat 🌹

#102 [#98] 인증코드 뷰 짜기
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Constants/Storyboard.swift
  Journey/Journey/Resources/Constants/ViewController.swift
  Journey/Journey/Resources/Storyboards/Auth/Code.storyboard
  Journey/Journey/Sources/ViewControllers/Auth/CodeViewController.swift
Labels: choyi 🎱, feat 🌹

#103 [#100] 새 비밀번호 뷰 짜기
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Constants/Storyboard.swift
  Journey/Journey/Resources/Constants/ViewController.swift
  Journey/Journey/Resources/Storyboards/Auth/NewPassword.storyboard
  Journey/Journey/Sources/ViewControllers/Auth/NewPasswordViewController.swift
Labels: choyi 🎱, feat 🌹

#105 [#77] Course 뷰 수정사항 반영
  Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.swift
  Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.xib
  Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.swift
  Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.xib
  Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.swift
  Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.xib
Labels: choyi 🎱, feat 🌹

#107 [#83] 소확행 구경하기뷰 수정사항 반영
  Journey/Journey/Resources/Assets.xcassets/floating.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/floating.imageset/floating.png
  Journey/Journey/Resources/Assets.xcassets/floating.imageset/floating@2x.png
  Journey/Journey/Resources/Assets.xcassets/floating.imageset/floating@3x.png
  Journey/Journey/Resources/Storyboards/Feed/Feed.storyboard
  Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
Labels: feat 🌹, yezi✨

#109 [#106] Course Library View 통신 연결
  Journey/.swiftlint.yml
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Constants/URL.swift
  Journey/Journey/Sources/APIModels/Course.swift
  Journey/Journey/Sources/APIServices/ChallengeAPI/ChallengeAPI.swift
  Journey/Journey/Sources/APIServices/ChallengeAPI/ChallengeService.swift
  Journey/Journey/Sources/APIServices/CourseAPI/CourseAPI.swift
  Journey/Journey/Sources/APIServices/CourseAPI/CourseService.swift
  Journey/Journey/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
  Journey/Journey/Sources/ViewModels/CourseListViewModel.swift
  Journey/Journey/Sources/ViewModels/ViewModelState.swift
Labels: choyi 🎱, feat 🌹

#110 [#64] SignUpSecond 뷰 Component 배치
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Assets.xcassets/indicator2.imageset/indicator2@2x.png
  Journey/Journey/Resources/Constants/Storyboard.swift
  Journey/Journey/Resources/Constants/ViewController.swift
  Journey/Journey/Resources/Storyboards/Auth/SignUpSecond.storyboard
  Journey/Journey/Sources/AppModels/AppYear.swift
  Journey/Journey/Sources/ViewControllers/Auth/SignUpSecondViewController.swift
  Journey/Journey/Sources/Views/YearPickerViewController.swift
  Journey/Journey/Sources/Views/YearPickerViewController.xib
Labels: feat 🌹, seungchan🗻

#113 [#111] SignUpThird 뷰 Component 배치
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Assets.xcassets/IMG_1838.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/IMG_1838.imageset/IMG_1838.jpg
  Journey/Journey/Resources/Assets.xcassets/indicator2.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/indicator2.imageset/indicator2.png
  Journey/Journey/Resources/Assets.xcassets/indicator2.imageset/indicator2@3x.png
  Journey/Journey/Resources/Assets.xcassets/indicator3.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/indicator3.imageset/indicator3.png
  Journey/Journey/Resources/Assets.xcassets/indicator3.imageset/indicator3@2x.png
  Journey/Journey/Resources/Assets.xcassets/indicator3.imageset/indicator3@3x.png
  Journey/Journey/Resources/Assets.xcassets/stampSampling.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/stampSampling.imageset/stampSampling.png
  Journey/Journey/Resources/Assets.xcassets/stampSampling.imageset/stampSampling@2x.png
  Journey/Journey/Resources/Assets.xcassets/stampSampling.imageset/stampSampling@3x.png
  Journey/Journey/Resources/Constants/Storyboard.swift
  Journey/Journey/Resources/Constants/ViewController.swift
  Journey/Journey/Resources/Storyboards/Auth/SignUpThird.storyboard
  Journey/Journey/Sources/SceneDelegate.swift
  Journey/Journey/Sources/ViewControllers/Auth/SignUpFirstViewController.swift
  Journey/Journey/Sources/ViewControllers/Auth/SignUpThirdViewController.swift
Labels: feat 🌹, seungchan🗻

#114 [#NON_ISSUE] conflict 해결
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Constants/ViewController.swift
  Journey/Journey/Sources/APIServices/CourseAPI/CourseAPI.swift
  Journey/Journey/Sources/SceneDelegate.swift
  Journey/Journey/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
Labels: chore 🛠, choyi 🎱

#117 [#115] 소확행 디테일뷰 수정사항 반영
  Journey/Journey/Resources/Assets.xcassets/gnbIconTrash.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/gnbIconTrash.imageset/gnbIconTrash.png
  Journey/Journey/Resources/Assets.xcassets/gnbIconTrash.imageset/gnbIconTrash@2x.png
  Journey/Journey/Resources/Assets.xcassets/gnbIconTrash.imageset/gnbIconTrash@3x.png
  Journey/Journey/Resources/Assets.xcassets/icnHeart.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/icnHeart.imageset/icnHeart.png
  Journey/Journey/Resources/Assets.xcassets/icnHeart.imageset/icnHeart@2x.png
  Journey/Journey/Resources/Assets.xcassets/icnHeart.imageset/icnHeart@3x.png
  Journey/Journey/Resources/Storyboards/Feed/FeedDetail.storyboard
  Journey/Journey/Sources/ViewControllers/Feed/FeedDetailViewController.swift
Labels: feat 🌹, yezi✨

#124 [#88] 메인뷰 서버 연결
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Storyboards/Home/Home.storyboard
  Journey/Journey/Sources/APIModels/Home.swift
  Journey/Journey/Sources/APIServices/HomeAPI/HomeAPI.swift
  Journey/Journey/Sources/APIServices/HomeAPI/HomeService.swift
  Journey/Journey/Sources/ViewControllers/Home/HomeViewController.swift
Labels: feat 🌹, yezi✨

#126 [#29] 챌린지뷰 짜기
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Storyboards/Challenge/Challenge.storyboard
  Journey/Journey/Sources/Extensions/UIDevice+Extension.swift
  Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift
Labels: feat 🌹, seungchan🗻

#129 [#127] 로그인뷰 오토레이아웃 수정
  Journey/Journey/Resources/Storyboards/Auth/Login.storyboard
Labels: refactor 🥲, seungchan🗻

#130 [#128] SignUpThird 뷰 수정
  Journey/Journey/Resources/Storyboards/Auth/SignUpThird.storyboard
  Journey/Journey/Sources/ViewControllers/Auth/SignUpThirdViewController.swift
Labels: refactor 🥲, seungchan🗻

#132 [#131] SignUpFirst 오토레이아웃 수정
  Journey/Journey/Resources/Storyboards/Auth/SignUpFirst.storyboard
Labels: refactor 🥲, seungchan🗻

#134 [#133] SignUpSecond 오토레이아웃 수정
  Journey/Journey/Resources/Storyboards/Auth/SignUpSecond.storyboard
Labels: refactor 🥲, seungchan🗻

#142 [#140] 회원가입 뷰들 상단, 좌우 constraint 변경
  Journey/Journey/Resources/Storyboards/Auth/Login.storyboard
  Journey/Journey/Resources/Storyboards/Auth/SignUpFirst.storyboard
  Journey/Journey/Resources/Storyboards/Auth/SignUpSecond.storyboard
  Journey/Journey/Resources/Storyboards/Auth/SignUpThird.storyboard
  Journey/Journey/Sources/ViewControllers/Auth/SignUpFirstViewController.swift
  Journey/Journey/Sources/ViewControllers/Auth/SignUpThirdViewController.swift
Labels: seungchan🗻, style 👗

#147 [#144] 로그인뷰 서버연결
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Sources/APIServices/AuthAPI/LoginAPI.swift
  Journey/Journey/Sources/APIServices/AuthAPI/LoginService.swift
  Journey/Journey/Sources/ViewControllers/Auth/LoginViewController.swift
Labels: feat 🌹, seungchan🗻

#148 [#141] 코스, 챌린지 완료 팝업 뷰
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Assets.xcassets/IMG_5732.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/IMG_5732.imageset/IMG_5732-1.PNG
  Journey/Journey/Resources/Assets.xcassets/IMG_5732.imageset/IMG_5732-2.PNG
  Journey/Journey/Resources/Assets.xcassets/IMG_5732.imageset/IMG_5732.PNG
  Journey/Journey/Resources/Assets.xcassets/floatingSeungchan.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/floatingSeungchan.imageset/IMG_5711-1.jpg
  Journey/Journey/Resources/Assets.xcassets/floatingSeungchan.imageset/IMG_5711-2.jpg
  Journey/Journey/Resources/Assets.xcassets/floatingSeungchan.imageset/IMG_5711.jpg
  Journey/Journey/Resources/Constants/Xib.swift
  Journey/Journey/Sources/ViewControllers/PopUp/AnimationPopUpViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/AnimationPopUpViewController.xib
  Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.xib
Labels: choyi 🎱, feat 🌹

#153 [#125] 소확행 구경하기 서버 연결
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Assets.xcassets/IconCongratulations.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/IconCongratulations.imageset/IconCongratulations.png
  Journey/Journey/Resources/Assets.xcassets/IconCongratulations.imageset/IconCongratulations@2x.png
  Journey/Journey/Resources/Assets.xcassets/IconCongratulations.imageset/IconCongratulations@3x.png
  Journey/Journey/Resources/Assets.xcassets/bgGraphicHappy.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/bgGraphicHappy.imageset/bgGraphicHappy.png
  Journey/Journey/Resources/Assets.xcassets/bgGraphicHappy.imageset/bgGraphicHappy@2x.png
  Journey/Journey/Resources/Assets.xcassets/bgGraphicHappy.imageset/bgGraphicHappy@3x.png
  Journey/Journey/Resources/Assets.xcassets/btnFilter.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/btnFilter.imageset/btnFilter.png
  Journey/Journey/Resources/Assets.xcassets/btnFilter.imageset/btnFilter@2x.png
  Journey/Journey/Resources/Assets.xcassets/btnFilter.imageset/btnFilter@3x.png
  Journey/Journey/Resources/Assets.xcassets/icnHeartfull.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/icnHeartfull.imageset/icnHeartfull.png
  Journey/Journey/Resources/Assets.xcassets/icnHeartfull.imageset/icnHeartfull@2x.png
  Journey/Journey/Resources/Assets.xcassets/icnHeartfull.imageset/icnHeartfull@3x.png
  Journey/Journey/Resources/Assets.xcassets/imgLock.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/imgLock.imageset/imgLock.png
  Journey/Journey/Resources/Assets.xcassets/imgLock.imageset/imgLock@2x.png
  Journey/Journey/Resources/Assets.xcassets/imgLock.imageset/imgLock@3x.png
  Journey/Journey/Resources/Assets.xcassets/imgUnlock.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/imgUnlock.imageset/imgUnlock.png
  Journey/Journey/Resources/Assets.xcassets/imgUnlock.imageset/imgUnlock@2x.png
  Journey/Journey/Resources/Assets.xcassets/imgUnlock.imageset/imgUnlock@3x.png
  Journey/Journey/Resources/Constants/URL.swift
  Journey/Journey/Resources/Storyboards/Feed/Feed.storyboard
  Journey/Journey/Sources/APIModels/Feed.swift
  Journey/Journey/Sources/APIServices/FeedAPI/FeedAPI.swift
  Journey/Journey/Sources/APIServices/FeedAPI/FeedService.swift
  Journey/Journey/Sources/Cells/FeedCollectionView/ContentsCollectionViewCell.swift
  Journey/Journey/Sources/Extensions/UIFont+Extension.swift
  Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
  Journey/Journey/Sources/Views/FeedHeaderView.swift
  Journey/Journey/Sources/Views/FeedHeaderView.xib
  Journey/Podfile
  Journey/Podfile.lock
Labels: feat 🌹, yezi✨

#156 [#151] reward view 뷰 변경사항 반영
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Assets.xcassets/flwGraphic.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/flwGraphic.imageset/flwGraphic.png
  Journey/Journey/Resources/Assets.xcassets/flwGraphic.imageset/flwGraphic@2x.png
  Journey/Journey/Resources/Assets.xcassets/flwGraphic.imageset/flwGraphic@3x.png
  Journey/Journey/Resources/Constants/Image.swift
  Journey/Journey/Sources/AppModels/Property.swift
  Journey/Journey/Sources/Cells/MedalCollectionView/MedalCollectionViewCell.swift
  Journey/Journey/Sources/Cells/MedalCollectionView/MedalCollectionViewCell.xib
  Journey/Journey/Sources/Extensions/UIColor+Extension.swift
  Journey/Journey/Sources/Views/MedalCollectionReusableView.xib
Labels: choyi 🎱, style 👗

#161 [#159] 메인 홈 activity indicator 추가
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Sources/Extensions/UIViewController+Extension.swift
  Journey/Journey/Sources/ViewControllers/Home/HomeViewController.swift
Labels: choyi 🎱, feat 🌹

#160 [#155] 챌린지 시작 전 뷰
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Assets.xcassets/bgcrsselect.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/bgcrsselect.imageset/bgcrsselect.png
  Journey/Journey/Resources/Assets.xcassets/bgcrsselect.imageset/bgcrsselect@2x.png
  Journey/Journey/Resources/Assets.xcassets/bgcrsselect.imageset/bgcrsselect@3x.png
  Journey/Journey/Resources/Constants/Storyboard.swift
  Journey/Journey/Resources/Constants/ViewController.swift
  Journey/Journey/Resources/Storyboards/Challenge/EmptyChallenge.storyboard
  Journey/Journey/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
  Journey/Journey/Sources/ViewControllers/Challenge/EmptyChallengeViewController.swift
Labels: choyi 🎱, feat 🌹

#163 [#143] 소확행 작성 완료 팝업 뷰
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Assets.xcassets/happyCFaceGraphic1.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/happyCFaceGraphic1.imageset/happyCFaceGraphic1.png
  Journey/Journey/Resources/Assets.xcassets/happyCFaceGraphic1.imageset/happyCFaceGraphic1@2x.png
  Journey/Journey/Resources/Assets.xcassets/happyCFaceGraphic1.imageset/happyCFaceGraphic1@3x.png
  Journey/Journey/Resources/Assets.xcassets/happyCFaceGraphic2.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/happyCFaceGraphic2.imageset/happyCFaceGraphic2.png
  Journey/Journey/Resources/Assets.xcassets/happyCFaceGraphic2.imageset/happyCFaceGraphic2@2x.png
  Journey/Journey/Resources/Assets.xcassets/happyCFaceGraphic2.imageset/happyCFaceGraphic2@3x.png
  Journey/Journey/Resources/Assets.xcassets/happyCFaceGraphic3.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/happyCFaceGraphic3.imageset/happyCFaceGraphic3.png
  Journey/Journey/Resources/Assets.xcassets/happyCFaceGraphic3.imageset/happyCFaceGraphic3@2x.png
  Journey/Journey/Resources/Assets.xcassets/happyCFaceGraphic3.imageset/happyCFaceGraphic3@3x.png
  Journey/Journey/Resources/Constants/Image.swift
  Journey/Journey/Resources/Constants/Xib.swift
  Journey/Journey/Sources/ViewControllers/PopUp/HappyPopUpViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/HappyPopUpViewController.xib
  Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.xib
Labels: choyi 🎱, feat 🌹

#165 [#164] 코스 라이브러리 셀 변경사항 적용
  Journey/Journey/Resources/Assets.xcassets/courseLibrarySeparator.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/courseLibrarySeparator.imageset/courseLibrarySeparator.png
  Journey/Journey/Resources/Assets.xcassets/courseLibrarySeparator.imageset/courseLibrarySeparator@2x.png
  Journey/Journey/Resources/Assets.xcassets/courseLibrarySeparator.imageset/courseLibrarySeparator@3x.png
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.swift
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.xib
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.swift
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.xib
Labels: choyi 🎱, feat 🌹

#168 [#149] 회원가입 서버통신
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Storyboards/Auth/SignUpThird.storyboard
  Journey/Journey/Sources/APIServices/AuthAPI/SignUpAPI.swift
  Journey/Journey/Sources/APIServices/AuthAPI/SignUpService.swift
  Journey/Journey/Sources/AppModels/SignUpUser.swift
  Journey/Journey/Sources/ViewControllers/Auth/SignUpFirstViewController.swift
  Journey/Journey/Sources/ViewControllers/Auth/SignUpSecondViewController.swift
  Journey/Journey/Sources/ViewControllers/Auth/SignUpThirdViewController.swift
Labels: feat 🌹, seungchan🗻

#172 [#169] 회원가입 뷰 코드 수정
  Journey/Journey/Sources/APIServices/AuthAPI/SignUpAPI.swift
  Journey/Journey/Sources/ViewControllers/Auth/SignUpThirdViewController.swift
Labels: chore 🛠, seungchan🗻

#174 [#157] 메인뷰 분기 처리
  Journey/Journey/Resources/Assets.xcassets/icnMedal.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/icnMedal.imageset/icnMedal.png
  Journey/Journey/Resources/Assets.xcassets/icnMedal.imageset/icnMedal@2x.png
  Journey/Journey/Resources/Assets.xcassets/icnMedal.imageset/icnMedal@3x.png
  Journey/Journey/Resources/Assets.xcassets/icnSetting.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/icnSetting.imageset/icnSetting.png
  Journey/Journey/Resources/Assets.xcassets/icnSetting.imageset/icnSetting@2x.png
  Journey/Journey/Resources/Assets.xcassets/icnSetting.imageset/icnSetting@3x.png
  Journey/Journey/Resources/Assets.xcassets/lv1.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/lv1.imageset/lv1.png
  Journey/Journey/Resources/Assets.xcassets/lv1.imageset/lv1@2x.png
  Journey/Journey/Resources/Assets.xcassets/lv1.imageset/lv1@3x.png
  Journey/Journey/Resources/Assets.xcassets/lv2.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/lv2.imageset/lv2 1.png
  Journey/Journey/Resources/Assets.xcassets/lv2.imageset/lv2 1@2x.png
  Journey/Journey/Resources/Assets.xcassets/lv2.imageset/lv2 1@3x.png
  Journey/Journey/Resources/Assets.xcassets/lv3.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/lv3.imageset/lv3 1.png
  Journey/Journey/Resources/Assets.xcassets/lv3.imageset/lv3 1@2x.png
  Journey/Journey/Resources/Assets.xcassets/lv3.imageset/lv3 1@3x.png
  Journey/Journey/Resources/Assets.xcassets/lv4.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/lv4.imageset/lv4.png
  Journey/Journey/Resources/Assets.xcassets/lv4.imageset/lv4@2x.png
  Journey/Journey/Resources/Assets.xcassets/lv4.imageset/lv4@3x.png
  Journey/Journey/Resources/Constants/Image.swift
  Journey/Journey/Resources/Storyboards/Home/Home.storyboard
  Journey/Journey/Sources/ViewControllers/Home/HomeViewController.swift
Labels: feat 🌹, yezi✨

#178 [#170] UserDefaults에 jwt, fcm token 저장하기
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Sources/APIServices/AuthAPI/LoginService.swift
  Journey/Journey/Sources/APIServices/ChallengeAPI/ChallengeService.swift
  Journey/Journey/Sources/APIServices/CourseAPI/CourseService.swift
  Journey/Journey/Sources/APIServices/FeedAPI/FeedService.swift
  Journey/Journey/Sources/APIServices/HomeAPI/HomeService.swift
  Journey/Journey/Sources/AppDelegate.swift
  Journey/Journey/Sources/SceneDelegate.swift
  Journey/Journey/Sources/ViewControllers/Auth/LoginViewController.swift
Labels: choyi 🎱, feat 🌹

#186 [#185] 모델 변경사항 반영
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Sources/APIModels/Challenge.swift
  Journey/Journey/Sources/APIModels/Community.swift
  Journey/Journey/Sources/APIModels/Course.swift
  Journey/Journey/Sources/APIModels/Feed.swift
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.swift
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.swift
  Journey/Journey/Sources/ViewControllers/Auth/LoginViewController.swift
  Journey/Journey/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
  Journey/Journey/Sources/ViewControllers/Challenge/CourseViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
  Journey/Journey/Sources/ViewControllers/Home/MedalViewController.swift
Labels: choyi 🎱, refactor 🥲

#181 [#180] 앱아이콘 추가
  Journey/Journey/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.png
  Journey/Journey/Resources/Assets.xcassets/AppIcon.appiconset/Icon-120.png
  Journey/Journey/Resources/Assets.xcassets/AppIcon.appiconset/Icon-121.png
  Journey/Journey/Resources/Assets.xcassets/AppIcon.appiconset/Icon-152.png
  Journey/Journey/Resources/Assets.xcassets/AppIcon.appiconset/Icon-167.png
  Journey/Journey/Resources/Assets.xcassets/AppIcon.appiconset/Icon-180.png
  Journey/Journey/Resources/Assets.xcassets/AppIcon.appiconset/Icon-20.png
  Journey/Journey/Resources/Assets.xcassets/AppIcon.appiconset/Icon-29.png
  Journey/Journey/Resources/Assets.xcassets/AppIcon.appiconset/Icon-40.png
  Journey/Journey/Resources/Assets.xcassets/AppIcon.appiconset/Icon-41.png
  Journey/Journey/Resources/Assets.xcassets/AppIcon.appiconset/Icon-42.png
  Journey/Journey/Resources/Assets.xcassets/AppIcon.appiconset/Icon-58.png
  Journey/Journey/Resources/Assets.xcassets/AppIcon.appiconset/Icon-59.png
  Journey/Journey/Resources/Assets.xcassets/AppIcon.appiconset/Icon-60.png
  Journey/Journey/Resources/Assets.xcassets/AppIcon.appiconset/Icon-76.png
  Journey/Journey/Resources/Assets.xcassets/AppIcon.appiconset/Icon-80.png
  Journey/Journey/Resources/Assets.xcassets/AppIcon.appiconset/Icon-81.png
  Journey/Journey/Resources/Assets.xcassets/AppIcon.appiconset/Icon-87.png
Labels: chore 🛠, choyi 🎱

#182 [#177] 환경설정 뷰 만들기
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Constants/Storyboard.swift
  Journey/Journey/Resources/Constants/ViewController.swift
  Journey/Journey/Resources/Storyboards/Home/Setting.storyboard
  Journey/Journey/Sources/Cells/SettingTableViewCell.swift
  Journey/Journey/Sources/ViewControllers/Home/HomeViewController.swift
  Journey/Journey/Sources/ViewControllers/Home/SettingViewController.swift
Labels: choyi 🎱, feat 🌹

#187 [#173] 챌린지뷰 서버통신
  Journey/Journey/Sources/APIServices/ChallengeAPI/ChallengeAPI.swift
  Journey/Journey/Sources/APIServices/ChallengeAPI/ChallengeService.swift
  Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift
  Journey/Journey/Sources/ViewControllers/Home/HomeViewController.swift
Labels: feat 🌹, seungchan🗻

#192 [#184] 내 서랍장 서버 연결
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Assets.xcassets/bgemptyhappy.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/bgemptyhappy.imageset/bgemptyhappy.png
  Journey/Journey/Resources/Assets.xcassets/bgemptyhappy.imageset/bgemptyhappy@2x.png
  Journey/Journey/Resources/Assets.xcassets/bgemptyhappy.imageset/bgemptyhappy@3x.png
  Journey/Journey/Resources/Assets.xcassets/btnDown.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/btnDown.imageset/btnDown.png
  Journey/Journey/Resources/Assets.xcassets/btnDown.imageset/btnDown@2x.png
  Journey/Journey/Resources/Assets.xcassets/btnDown.imageset/btnDown@3x.png
  Journey/Journey/Resources/Storyboards/Feed/MyDrawer.storyboard
  Journey/Journey/Sources/APIModels/MyDrawer.swift
  Journey/Journey/Sources/APIServices/FeedAPI/FeedAPI.swift
  Journey/Journey/Sources/APIServices/FeedAPI/FeedService.swift
  Journey/Journey/Sources/Cells/FeedCollectionView/ContentsCollectionViewCell.swift
  Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/MyDrawerViewController.swift
  Journey/Journey/Sources/Views/DatePickerViewController.swift
  Journey/Journey/Sources/Views/DatePickerViewController.xib
  Journey/Journey/Sources/Views/MyDrawerCollectionReusableView.swift
  Journey/Journey/Sources/Views/MyDrawerCollectionReusableView.xib
Labels: feat 🌹, yezi✨

#193 [#158] 코스 라이브러리에서 코스 시작/변경 통신 연결
  Journey/Journey/Resources/Constants/Xib.swift
  Journey/Journey/Sources/APIServices/CourseAPI/CourseAPI.swift
  Journey/Journey/Sources/APIServices/CourseAPI/CourseService.swift
  Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift
  Journey/Journey/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.swift
Labels: choyi 🎱, feat 🌹

#196 [#191] 스플래시 뷰
  Journey/Journey/Resources/Assets.xcassets/spashTypoLogo.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/spashTypoLogo.imageset/spashTypoLogo.png
  Journey/Journey/Resources/Assets.xcassets/spashTypoLogo.imageset/spashTypoLogo@2x.png
  Journey/Journey/Resources/Assets.xcassets/spashTypoLogo.imageset/spashTypoLogo@3x.png
  Journey/Journey/Resources/Assets.xcassets/splashJourney.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/splashJourney.imageset/splashJourney.png
  Journey/Journey/Resources/Assets.xcassets/splashJourney.imageset/splashJourney@2x.png
  Journey/Journey/Resources/Assets.xcassets/splashJourney.imageset/splashJourney@3x.png
  Journey/Journey/Resources/Assets.xcassets/splashTypo.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/splashTypo.imageset/splashTypo.png
  Journey/Journey/Resources/Assets.xcassets/splashTypo.imageset/splashTypo@2x.png
  Journey/Journey/Resources/Assets.xcassets/splashTypo.imageset/splashTypo@3x.png
  Journey/Journey/Resources/Storyboards/Base.lproj/LaunchScreen.storyboard
Labels: choyi 🎱, feat 🌹

#198 [#176] home 데이터 course 속성 optional 처리
  Journey/Journey/Sources/APIModels/Home.swift
  Journey/Journey/Sources/ViewControllers/Home/HomeViewController.swift
Labels: feat 🌹, yezi✨

#203 [#201] 챌린지 뷰 코스 여부 분기
  Journey/Journey/Resources/Storyboards/Challenge/Challenge.storyboard
  Journey/Journey/Resources/Storyboards/Challenge/EmptyChallenge.storyboard
  Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift
Labels: choyi 🎱, feat 🌹

#199 [#138] 코스 속성 따라 이미지, 배경 색 변경
  Journey/Journey/Resources/Storyboards/Base.lproj/LaunchScreen.storyboard
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.swift
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.xib
  Journey/Journey/Sources/Extensions/UIColor+Extension.swift
  Journey/Journey/Sources/ViewControllers/Home/MedalViewController.swift
Labels: choyi 🎱, feat 🌹

#200 [#188] 탭바 아이콘 변경
  Journey/Journey/Resources/Assets.xcassets/challengeIcon.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/challengeIcon.imageset/challengeIcon.png
  Journey/Journey/Resources/Assets.xcassets/challengeIcon.imageset/challengeIcon@2x.png
  Journey/Journey/Resources/Assets.xcassets/challengeIcon.imageset/challengeIcon@3x.png
  Journey/Journey/Resources/Assets.xcassets/feedIcon.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/feedIcon.imageset/feedIcon.png
  Journey/Journey/Resources/Assets.xcassets/feedIcon.imageset/feedIcon@2x.png
  Journey/Journey/Resources/Assets.xcassets/feedIcon.imageset/feedIcon@3x.png
  Journey/Journey/Resources/Assets.xcassets/homeIcon.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/homeIcon.imageset/homeIcon.png
  Journey/Journey/Resources/Assets.xcassets/homeIcon.imageset/homeIcon@2x.png
  Journey/Journey/Resources/Assets.xcassets/homeIcon.imageset/homeIcon@3x.png
  Journey/Journey/Resources/Storyboards/Challenge/Challenge.storyboard
  Journey/Journey/Resources/Storyboards/Feed/Feed.storyboard
  Journey/Journey/Resources/Storyboards/Home/Home.storyboard
  Journey/Journey/Resources/Storyboards/Tabbar.storyboard
Labels: choyi 🎱, feat 🌹

#202 [#175] Login뷰 수정
  Journey/Journey/Resources/Assets.xcassets/imageKey.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/imageKey.imageset/imageKey.png
  Journey/Journey/Resources/Assets.xcassets/imageKey.imageset/imageKey@2x.png
  Journey/Journey/Resources/Assets.xcassets/imageKey.imageset/imageKey@3x.png
  Journey/Journey/Resources/Assets.xcassets/imageMessage.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/imageMessage.imageset/imageMessage.png
  Journey/Journey/Resources/Assets.xcassets/imageMessage.imageset/imageMessage@2x.png
  Journey/Journey/Resources/Assets.xcassets/imageMessage.imageset/imageMessage@3x.png
  Journey/Journey/Resources/Assets.xcassets/loginJourney.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/loginJourney.imageset/loginJourney.png
  Journey/Journey/Resources/Assets.xcassets/loginJourney.imageset/loginJourney@2x.png
  Journey/Journey/Resources/Assets.xcassets/loginJourney.imageset/loginJourney@3x.png
  Journey/Journey/Resources/Assets.xcassets/loginXButton.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/loginXButton.imageset/loginXButton.png
  Journey/Journey/Resources/Assets.xcassets/loginXButton.imageset/loginXButton@2x.png
  Journey/Journey/Resources/Assets.xcassets/loginXButton.imageset/loginXButton@3x.png
  Journey/Journey/Resources/Storyboards/Auth/Login.storyboard
  Journey/Journey/Sources/ViewControllers/Auth/LoginViewController.swift
Labels: refactor 🥲, seungchan🗻

#204 [#162] 소확행 상세보기 서버 연결
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic1.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic1.imageset/imgFaceGraphic1.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic1.imageset/imgFaceGraphic1@2x.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic1.imageset/imgFaceGraphic1@3x.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic2.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic2.imageset/imgFaceGraphic2.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic2.imageset/imgFaceGraphic2@2x.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic2.imageset/imgFaceGraphic2@3x.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic3.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic3.imageset/imgFaceGraphic3.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic3.imageset/imgFaceGraphic3@2x.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic3.imageset/imgFaceGraphic3@3x.png
  Journey/Journey/Resources/Constants/Image.swift
  Journey/Journey/Resources/Storyboards/Feed/FeedDetail.storyboard
  Journey/Journey/Sources/APIModels/FeedDetail.swift
  Journey/Journey/Sources/APIServices/FeedAPI/FeedAPI.swift
  Journey/Journey/Sources/APIServices/FeedAPI/FeedService.swift
  Journey/Journey/Sources/ViewControllers/Feed/FeedDetailViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
Labels: feat 🌹, yezi✨

#205 [#197] course library cell dynamic height
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.swift
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.xib
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.swift
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.xib
  Journey/Journey/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
Labels: choyi 🎱, feat 🌹

#207 [#152] 소확행 작성 버튼 분기 팝업
  Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
  Journey/Journey/Sources/Views/FeedHeaderView.swift
  Journey/Journey/Sources/Views/FeedHeaderView.xib
Labels: feat 🌹, yezi✨

#208 [#206] 챌린지, 코스 완료 팝업 이미지
  Journey/Journey/Resources/Assets.xcassets/crsGraphic.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/crsGraphic.imageset/crsGraphic.png
  Journey/Journey/Resources/Assets.xcassets/crsGraphic.imageset/crsGraphic@2x.png
  Journey/Journey/Resources/Assets.xcassets/crsGraphic.imageset/crsGraphic@3x.png
  Journey/Journey/Resources/Assets.xcassets/graphicCongrats.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/graphicCongrats.imageset/graphicCongrats.png
  Journey/Journey/Resources/Assets.xcassets/graphicCongrats.imageset/graphicCongrats@2x.png
  Journey/Journey/Resources/Assets.xcassets/graphicCongrats.imageset/graphicCongrats@3x.png
  Journey/Journey/Resources/Storyboards/Challenge/Challenge.storyboard
  Journey/Journey/Resources/Storyboards/Challenge/Course.storyboard
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.xib
  Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift
  Journey/Journey/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/AnimationPopUpViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/AnimationPopUpViewController.xib
Labels: choyi 🎱, feat 🌹

#213 [#194, #195] 인증하기 팝업에 X 버튼, 인증 시점 변경
  Journey/Journey/Resources/Assets.xcassets/gnbIconX.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/gnbIconX.imageset/gnbIconX.png
  Journey/Journey/Resources/Assets.xcassets/gnbIconX.imageset/gnbIconX@2x.png
  Journey/Journey/Resources/Assets.xcassets/gnbIconX.imageset/gnbIconX@3x.png
  Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.xib
Labels: choyi 🎱, feat 🌹

#214 [#212] 리드미
  README.md
Labels: choyi 🎱, docs 📃

#224 [#223] login view layout bug fix
  Journey/Journey/Resources/Info.plist
  Journey/Journey/Resources/Storyboards/Auth/Login.storyboard
  Journey/Journey/Resources/Storyboards/Challenge/Challenge.storyboard
Labels: choyi 🎱, fix 🚨

#227 [#226] main 뷰 문구, 속성 아이콘 수정
  Journey/Journey/Resources/Storyboards/Home/Home.storyboard
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.xib
  Journey/Journey/Sources/ViewControllers/Home/HomeViewController.swift
Labels: choyi 🎱, feat 🌹

#231 [#145] 다크모드 점검
  Journey/Journey/Resources/Assets.xcassets/btnSide.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/courseLibrarySeparator.imageset/Contents.json
  Journey/Journey/Resources/Storyboards/Auth/Code.storyboard
  Journey/Journey/Resources/Storyboards/Auth/FindPassword.storyboard
  Journey/Journey/Resources/Storyboards/Auth/Login.storyboard
  Journey/Journey/Resources/Storyboards/Auth/NewPassword.storyboard
  Journey/Journey/Resources/Storyboards/Challenge/Challenge.storyboard
  Journey/Journey/Resources/Storyboards/Challenge/Course.storyboard
  Journey/Journey/Resources/Storyboards/Challenge/CourseLibrary.storyboard
  Journey/Journey/Resources/Storyboards/Home/Home.storyboard
  Journey/Journey/Resources/Storyboards/Home/Medal.storyboard
  Journey/Journey/Resources/Storyboards/Home/Setting.storyboard
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.xib
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.xib
  Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.xib
  Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.xib
  Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.xib
  Journey/Journey/Sources/Cells/FeedView/HashTagCollectionViewCell.xib
  Journey/Journey/Sources/Cells/MedalCollectionView/MedalCollectionViewCell.xib
  Journey/Journey/Sources/ViewControllers/Auth/LoginViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/AnimationPopUpViewController.xib
  Journey/Journey/Sources/ViewControllers/PopUp/HappyPopUpViewController.xib
  Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.xib
  Journey/Journey/Sources/Views/DatePickerViewController.xib
  Journey/Journey/Sources/Views/FeedHeaderView.xib
  Journey/Journey/Sources/Views/MedalCollectionReusableView.xib
  Journey/Journey/Sources/Views/MyDrawerCollectionReusableView.xib
  Journey/Journey/Sources/Views/YearPickerViewController.xib
Labels: choyi 🎱, style 👗

#220 [#219] 피커뷰 모달창 버튼 아이콘 수정
  Journey/Journey/Resources/Assets.xcassets/yearPickerX.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/yearPickerX.imageset/yearPickerX.png
  Journey/Journey/Resources/Assets.xcassets/yearPickerX.imageset/yearPickerX@2x.png
  Journey/Journey/Resources/Assets.xcassets/yearPickerX.imageset/yearPickerX@3x.png
  Journey/Journey/Sources/Views/YearPickerViewController.xib
Labels: refactor 🥲, seungchan🗻

#221 [#210] SignUpThird 뷰 정규식 넣기
  Journey/Journey/Resources/Storyboards/Auth/SignUpThird.storyboard
  Journey/Journey/Sources/ViewControllers/Auth/SignUpThirdViewController.swift
Labels: chore 🛠, seungchan🗻

#225 [#218] DoneCourse cell property, 코스 변경 로직
  Journey/Journey/Resources/Constants/Image.swift
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.swift
Labels: choyi 🎱, feat 🌹

#233 [#211] 소확행 글작성 서버 연결 완료
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic1circle.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic1circle.imageset/imgFaceGraphic1circle.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic1circle.imageset/imgFaceGraphic1circle@2x.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic1circle.imageset/imgFaceGraphic1circle@3x.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic2circle.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic2circle.imageset/imgFaceGraphic2circle.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic2circle.imageset/imgFaceGraphic2circle@2x.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic2circle.imageset/imgFaceGraphic2circle@3x.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic3circle.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic3circle.imageset/imgFaceGraphic3circle.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic3circle.imageset/imgFaceGraphic3circle@2x.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphic3circle.imageset/imgFaceGraphic3circle@3x.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphicIn1.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphicIn1.imageset/imgFaceGraphicIn1.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphicIn1.imageset/imgFaceGraphicIn1@2x.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphicIn1.imageset/imgFaceGraphicIn1@3x.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphicIn2.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphicIn2.imageset/imgFaceGraphicIn3.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphicIn2.imageset/imgFaceGraphicIn3@2x.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphicIn2.imageset/imgFaceGraphicIn3@3x.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphicIn3.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphicIn3.imageset/imgFaceGraphicIn3.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphicIn3.imageset/imgFaceGraphicIn3@2x.png
  Journey/Journey/Resources/Assets.xcassets/imgFaceGraphicIn3.imageset/imgFaceGraphicIn3@3x.png
  Journey/Journey/Resources/Constants/Image.swift
  Journey/Journey/Resources/Storyboards/Feed/Mood.storyboard
  Journey/Journey/Resources/Storyboards/Feed/Writing.storyboard
  Journey/Journey/Sources/APIModels/Writing.swift
  Journey/Journey/Sources/APIServices/FeedAPI/FeedAPI.swift
  Journey/Journey/Sources/APIServices/FeedAPI/FeedService.swift
  Journey/Journey/Sources/AppModels/AppDate.swift
  Journey/Journey/Sources/ViewControllers/Feed/MoodViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/WritingViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/HappyPopUpViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/HappyPopUpViewController.xib
Labels: feat 🌹, yezi✨

#243 [NON_ISSUE] compileXib error 해결
  Journey/Journey/Resources/Storyboards/Auth/SignUpFirst.storyboard
  Journey/Journey/Resources/Storyboards/Challenge/Challenge.storyboard
  Journey/Journey/Sources/Views/YearPickerViewController.xib
Labels: choyi 🎱, fix 🚨

#236 [#222] SignUpSecond 수정
  Journey/Journey/Resources/Storyboards/Auth/SignUpSecond.storyboard
  Journey/Journey/Sources/ViewControllers/Auth/SignUpSecondViewController.swift
  Journey/Journey/Sources/Views/YearPickerViewController.swift
Labels: refactor 🥲, seungchan🗻

#238 [#230] course 뷰 프로퍼티로 아이콘 분기처리
  Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.swift
  Journey/Journey/Sources/Cells/CourseTableView/EvenDayTableViewCell.xib
  Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.swift
  Journey/Journey/Sources/Cells/CourseTableView/FirstDayTableViewCell.xib
  Journey/Journey/Sources/Cells/CourseTableView/OddDayTableViewCell.swift
  Journey/Journey/Sources/ViewControllers/Challenge/CourseViewController.swift
Labels: choyi 🎱, feat 🌹

#239 [#237] SignUpFirst 수정
  Journey/Journey/Resources/Storyboards/Auth/SignUpFirst.storyboard
  Journey/Journey/Sources/ViewControllers/Auth/SignUpFirstViewController.swift
Labels: refactor 🥲, seungchan🗻

#240 [#217] 챌린지 뷰 초기에 label에 따라 bgView frame 수정이 안 되는 문제
  Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift
Labels: choyi 🎱, fix 🚨

#241 [#234] 소확행 삭제 로직 추가
  Journey/Journey/Resources/Constants/URL.swift
  Journey/Journey/Sources/APIServices/FeedAPI/FeedAPI.swift
  Journey/Journey/Sources/APIServices/FeedAPI/FeedService.swift
  Journey/Journey/Sources/ViewControllers/Feed/FeedDetailViewController.swift
Labels: feat 🌹, yezi✨

#244 [#216] 회원가입 뷰 네비게이션 바 init 함수 추가
  Journey/Journey/Resources/Storyboards/Auth/SignUpFirst.storyboard
  Journey/Journey/Sources/ViewControllers/Auth/SignUpSecondViewController.swift
  Journey/Journey/Sources/ViewControllers/Auth/SignUpThirdViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/FeedDetailViewController.swift
Labels: choyi 🎱, style 👗

#246 [#242] 내 서랍장 request 형식 변경, 날짜 형식 변경, 해피 팝업 수정
  Journey/Journey/Resources/Assets.xcassets/IMG_5732.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/IMG_5732.imageset/IMG_5732-1.PNG
  Journey/Journey/Resources/Assets.xcassets/IMG_5732.imageset/IMG_5732-2.PNG
  Journey/Journey/Resources/Assets.xcassets/IMG_5732.imageset/IMG_5732.PNG
  Journey/Journey/Resources/Storyboards/Feed/Mood.storyboard
  Journey/Journey/Resources/Storyboards/Feed/Writing.storyboard
  Journey/Journey/Sources/AppModels/AppDate.swift
  Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/MoodViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/MyDrawerViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/WritingViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/HappyPopUpViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/HappyPopUpViewController.xib
  Journey/Journey/Sources/Views/DatePickerViewController.swift
Labels: feat 🌹, yezi✨

#247 [#245] 전체 오토레이아웃, 다크모드 점검
  Journey/Journey/Resources/Info.plist
  Journey/Journey/Resources/Storyboards/Auth/Code.storyboard
  Journey/Journey/Resources/Storyboards/Auth/FindPassword.storyboard
  Journey/Journey/Resources/Storyboards/Auth/Login.storyboard
  Journey/Journey/Resources/Storyboards/Auth/NewPassword.storyboard
  Journey/Journey/Resources/Storyboards/Auth/SignUpFirst.storyboard
  Journey/Journey/Resources/Storyboards/Auth/SignUpSecond.storyboard
  Journey/Journey/Resources/Storyboards/Auth/SignUpThird.storyboard
  Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/AnimationPopUpViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.xib
  Journey/Journey/Sources/Views/YearPickerViewController.xib
Labels: choyi 🎱, fix 🚨

#249 [#248] 글씨색 바꾸기, 패스워드 라벨 보이기
  Journey/Journey/Resources/Storyboards/Auth/Login.storyboard
  Journey/Journey/Resources/Storyboards/Auth/SignUpFirst.storyboard
  Journey/Journey/Sources/ViewControllers/Auth/SignUpFirstViewController.swift
  Journey/Journey/Sources/ViewControllers/Auth/SignUpSecondViewController.swift
  Journey/Journey/Sources/ViewControllers/Auth/SignUpThirdViewController.swift
Labels: refactor 🥲, seungchan🗻

#252 [#250] 이미지 없을 때 default 설정
  Journey/Journey/Resources/Assets.xcassets/happyfeedX.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/happyfeedX.imageset/happyfeedX.png
  Journey/Journey/Resources/Assets.xcassets/happyfeedX.imageset/happyfeedX@2x.png
  Journey/Journey/Resources/Assets.xcassets/happyfeedX.imageset/happyfeedX@3x.png
  Journey/Journey/Resources/Constants/Image.swift
  Journey/Journey/Sources/Views/DatePickerViewController.xib
Labels: feat 🌹, yezi✨

#253 [#251] 해시태그 인덱스 에러 수정
  Journey/Journey/Sources/ViewControllers/Feed/FeedDetailViewController.swift
Labels: feat 🌹, yezi✨

#255 [#254] default 이미지 조건 값 수정
  Journey/Journey/Sources/ViewControllers/Feed/FeedDetailViewController.swift
Labels: fix 🚨, yezi✨

#257 [#256] homeView life cycle 수정
  Journey/Journey/Sources/ViewControllers/Home/HomeViewController.swift
Labels: refactor 🥲, yezi✨

#259 [#258] 팝업 레이아웃 경고 수정
  Journey/Journey/Resources/Assets.xcassets/background.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/background.imageset/background-1.png
  Journey/Journey/Resources/Assets.xcassets/background.imageset/background-2.png
  Journey/Journey/Resources/Assets.xcassets/background.imageset/background.png
  Journey/Journey/Sources/ViewControllers/PopUp/HappyPopUpViewController.xib
Labels: fix 🚨, yezi✨

#261 [#260] 챌린지 완료 시 축하 컨페티 이미지 띄우기
  Journey/Journey/Resources/Assets.xcassets/stamp1confetti1.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/stamp1confetti1.imageset/stamp1confetti1.png
  Journey/Journey/Resources/Assets.xcassets/stamp1confetti1.imageset/stamp1confetti1@2x.png
  Journey/Journey/Resources/Assets.xcassets/stamp1confetti1.imageset/stamp1confetti1@3x.png
  Journey/Journey/Resources/Assets.xcassets/stamp1confetti2.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/stamp1confetti2.imageset/stamp1confetti2.png
  Journey/Journey/Resources/Assets.xcassets/stamp1confetti2.imageset/stamp1confetti2@2x.png
  Journey/Journey/Resources/Assets.xcassets/stamp1confetti2.imageset/stamp1confetti2@3x.png
  Journey/Journey/Resources/Assets.xcassets/stamp1confetti3.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/stamp1confetti3.imageset/stamp1confetti3.png
  Journey/Journey/Resources/Assets.xcassets/stamp1confetti3.imageset/stamp1confetti3@2x.png
  Journey/Journey/Resources/Assets.xcassets/stamp1confetti3.imageset/stamp1confetti3@3x.png
  Journey/Journey/Resources/Assets.xcassets/stamp1confetti4.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/stamp1confetti4.imageset/stamp1confetti4.png
  Journey/Journey/Resources/Assets.xcassets/stamp1confetti4.imageset/stamp1confetti4@2x.png
  Journey/Journey/Resources/Assets.xcassets/stamp1confetti4.imageset/stamp1confetti4@3x.png
  Journey/Journey/Resources/Assets.xcassets/stamp2confetti1.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/stamp2confetti1.imageset/stamp2confetti1.png
  Journey/Journey/Resources/Assets.xcassets/stamp2confetti1.imageset/stamp2confetti1@2x.png
  Journey/Journey/Resources/Assets.xcassets/stamp2confetti1.imageset/stamp2confetti1@3x.png
  Journey/Journey/Resources/Assets.xcassets/stamp2confetti2.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/stamp2confetti2.imageset/stamp2confetti2.png
  Journey/Journey/Resources/Assets.xcassets/stamp2confetti2.imageset/stamp2confetti2@2x.png
  Journey/Journey/Resources/Assets.xcassets/stamp2confetti2.imageset/stamp2confetti2@3x.png
  Journey/Journey/Resources/Assets.xcassets/stamp2confetti3.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/stamp2confetti3.imageset/stamp2confetti3.png
  Journey/Journey/Resources/Assets.xcassets/stamp2confetti3.imageset/stamp2confetti3@2x.png
  Journey/Journey/Resources/Assets.xcassets/stamp2confetti3.imageset/stamp2confetti3@3x.png
  Journey/Journey/Resources/Assets.xcassets/stamp2confetti4.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/stamp2confetti4.imageset/stamp2confetti4.png
  Journey/Journey/Resources/Assets.xcassets/stamp2confetti4.imageset/stamp2confetti4@2x.png
  Journey/Journey/Resources/Assets.xcassets/stamp2confetti4.imageset/stamp2confetti4@3x.png
  Journey/Journey/Resources/Assets.xcassets/stamp3confetti1Notch.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/stamp3confetti1Notch.imageset/stamp3confetti1Notch.png
  Journey/Journey/Resources/Assets.xcassets/stamp3confetti1Notch.imageset/stamp3confetti1Notch@2x.png
  Journey/Journey/Resources/Assets.xcassets/stamp3confetti1Notch.imageset/stamp3confetti1Notch@3x.png
  Journey/Journey/Resources/Assets.xcassets/stamp3confetti2Notch.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/stamp3confetti2Notch.imageset/stamp3confetti2Notch.png
  Journey/Journey/Resources/Assets.xcassets/stamp3confetti2Notch.imageset/stamp3confetti2Notch@2x.png
  Journey/Journey/Resources/Assets.xcassets/stamp3confetti2Notch.imageset/stamp3confetti2Notch@3x.png
  Journey/Journey/Resources/Assets.xcassets/stamp3confetti3Notch.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/stamp3confetti3Notch.imageset/stamp3confetti3Notch.png
  Journey/Journey/Resources/Assets.xcassets/stamp3confetti3Notch.imageset/stamp3confetti3Notch@2x.png
  Journey/Journey/Resources/Assets.xcassets/stamp3confetti3Notch.imageset/stamp3confetti3Notch@3x.png
  Journey/Journey/Resources/Assets.xcassets/stamp3confetti4Notch.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/stamp3confetti4Notch.imageset/stamp3confetti4Notch.png
  Journey/Journey/Resources/Assets.xcassets/stamp3confetti4Notch.imageset/stamp3confetti4Notch@2x.png
  Journey/Journey/Resources/Assets.xcassets/stamp3confetti4Notch.imageset/stamp3confetti4Notch@3x.png
  Journey/Journey/Resources/Storyboards/Challenge/Challenge.storyboard
  Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift
Labels: choyi 🎱, feat 🌹

#263 [#262] userMent index error
  Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift
Labels: choyi 🎱, fix 🚨

#265 [#146] activity indicator 추가
  Journey/Journey/Sources/ViewControllers/Auth/LoginViewController.swift
Labels: refactor 🥲, seungchan🗻

#264 [#146] Activity Indicator 붙이기
  Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift
  Journey/Journey/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
  Journey/Journey/Sources/ViewControllers/Challenge/CourseViewController.swift
  Journey/Journey/Sources/ViewControllers/Home/MedalViewController.swift
Labels: choyi 🎱, feat 🌹

#266 [#146] 로딩 인디케이터 추가
  Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/MyDrawerViewController.swift
Labels: feat 🌹, yezi✨

#268 [#267] EmptyCourse 뷰 앞으로 보내기
  Journey/Journey/Resources/Storyboards/Challenge/Challenge.storyboard
  Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift
Labels: choyi 🎱, fix 🚨

#270 [#269] 내 서랍장 날짜 버그 수정
  Journey/Journey/Sources/ViewControllers/Feed/MyDrawerViewController.swift
Labels: fix 🚨, yezi✨

#272 [#271] 팝업 에셋 설정
  Journey/Journey/Resources/Assets.xcassets/bgGraphicAlready.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/bgGraphicAlready.imageset/bgGraphicAlready.png
  Journey/Journey/Resources/Assets.xcassets/bgGraphicAlready.imageset/bgGraphicAlready@2x.png
  Journey/Journey/Resources/Assets.xcassets/bgGraphicAlready.imageset/bgGraphicAlready@3x.png
  Journey/Journey/Resources/Assets.xcassets/bgGraphicStart.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/bgGraphicStart.imageset/bgGraphicStart.png
  Journey/Journey/Resources/Assets.xcassets/bgGraphicStart.imageset/bgGraphicStart@2x.png
  Journey/Journey/Resources/Assets.xcassets/bgGraphicStart.imageset/bgGraphicStart@3x.png
  Journey/Journey/Resources/Assets.xcassets/bgGraphicYet.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/bgGraphicYet.imageset/bgGraphicYet.png
  Journey/Journey/Resources/Assets.xcassets/bgGraphicYet.imageset/bgGraphicYet@2x.png
  Journey/Journey/Resources/Assets.xcassets/bgGraphicYet.imageset/bgGraphicYet@3x.png
  Journey/Journey/Resources/Assets.xcassets/bgStartCourse.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/bgStartCourse.imageset/bgStartCourse.png
  Journey/Journey/Resources/Assets.xcassets/bgStartCourse.imageset/bgStartCourse@2x.png
  Journey/Journey/Resources/Assets.xcassets/bgStartCourse.imageset/bgStartCourse@3x.png
  Journey/Journey/Resources/Assets.xcassets/bgpopgiveup.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/bgpopgiveup.imageset/bgpopgiveup.png
  Journey/Journey/Resources/Assets.xcassets/bgpopgiveup.imageset/bgpopgiveup@2x.png
  Journey/Journey/Resources/Assets.xcassets/bgpopgiveup.imageset/bgpopgiveup@3x.png
  Journey/Journey/Resources/Assets.xcassets/bgpopok.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/bgpopok.imageset/bgpopok.png
  Journey/Journey/Resources/Assets.xcassets/bgpopok.imageset/bgpopok@2x.png
  Journey/Journey/Resources/Assets.xcassets/bgpopok.imageset/bgpopok@3x.png
  Journey/Journey/Resources/Constants/Image.swift
  Journey/Journey/Sources/ViewControllers/Challenge/ChallengeViewController.swift
  Journey/Journey/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
  Journey/Journey/Sources/ViewControllers/PopUp/PopUpViewController.swift
Labels: chore 🛠, feat 🌹, yezi✨

#274 [#273] 에셋 전반적으로 점검
  Journey/Journey/Resources/Assets.xcassets/lv1.imageset/lv1.png
  Journey/Journey/Resources/Assets.xcassets/lv1.imageset/lv1@2x.png
  Journey/Journey/Resources/Assets.xcassets/lv1.imageset/lv1@3x.png
  Journey/Journey/Resources/Constants/Image.swift
  Journey/Journey/Sources/Cells/FeedCollectionView/ContentsCollectionViewCell.swift
  Journey/Journey/Sources/Extensions/UIColor+Extension.swift
  Journey/Journey/Sources/ViewControllers/Feed/FeedDetailViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/MoodViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/WritingViewController.swift
  Journey/Journey/Sources/Views/FeedHeaderView.swift
Labels: chore 🛠, yezi✨
