Repository team-mohaeng/mohaeng-iOS, pull requests merged in 2021-11, with the labels that each got.

#503 [#502] testflight 1차 배포
  Mohaeng/Mohaeng.xcodeproj/project.pbxproj
  Mohaeng/Mohaeng/Sources/SceneDelegate.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/MyDrawerViewController.swift
  Mohaeng/Podfile.lock
Labels: chore 🛠, choyi 🎱

#506 [#501] 약관동의 웹페이지 연결
  Mohaeng/Mohaeng/Resources/Constants/Storyboard.swift
  Mohaeng/Mohaeng/Resources/Constants/ViewController.swift
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/Agree.storyboard
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/SignUpSecond.storyboard
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/AgreeViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpSecondViewController.swift
Labels: feat 🌹, seungchan🗻

#511 [#505] 2차 QA 반영
  Mohaeng/Mohaeng/Resources/Assets.xcassets/challengeCompleteEffect.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/challengeCompleteEffect.imageset/challengeCompleteEffect.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/challengeCompleteEffect.imageset/challengeCompleteEffect@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/challengeCompleteEffect.imageset/challengeCompleteEffect@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/grpXStartChallenge.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/grpXStartChallenge.imageset/grpXStartChallenge.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/grpXStartChallenge.imageset/grpXStartChallenge@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/grpXStartChallenge.imageset/grpXStartChallenge@3x.png
  Mohaeng/Mohaeng/Resources/Constants/Image.swift
  Mohaeng/Mohaeng/Resources/Constants/String.swift
  Mohaeng/Mohaeng/Sources/Cells/CourseTableView/EvenDayTableViewCell.swift
  Mohaeng/Mohaeng/Sources/Cells/CourseTableView/FirstDayTableViewCell.swift
  Mohaeng/Mohaeng/Sources/Cells/CourseTableView/OddDayTableViewCell.swift
  Mohaeng/Mohaeng/Sources/Cells/NotificationCollectionView/BubbleCollectionViewCell.xib
  Mohaeng/Mohaeng/Sources/Cells/NotificationCollectionView/ProfileBubbleCollectionViewCell.xib
  Mohaeng/Mohaeng/Sources/Extensions/UINavigationController+Extension.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Challenge/CourseViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/Mypage/CourseHistoryViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/Mypage/MyPageViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/NotificationViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/PopUp/ChallengeHelp/ChallengeHelpPopUpViewController.xib
  Mohaeng/Mohaeng/Sources/ViewControllers/PopUp/PopUpViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/PopUp/PopUpViewController.xib
  Mohaeng/Mohaeng/Sources/Views/ChallengeStampView.swift
  Mohaeng/Mohaeng/Sources/Views/ChallengeStampView.xib
  Mohaeng/Mohaeng/Sources/Views/CourseFooterView.swift
  Mohaeng/Podfile.lock
Labels: fix 🚨, choyi 🎱

#513 [#501] Agree 파일 추가
  Mohaeng/Mohaeng.xcodeproj/project.pbxproj
Labels: fix 🚨, seungchan🗻

#509 [#507] 모행 만든 사람들 뷰
  Mohaeng/Mohaeng.xcodeproj/project.pbxproj
  Mohaeng/Mohaeng/Resources/Assets.xcassets/makerBackground.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/makerBackground.imageset/makerBackground.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/makerBackground.imageset/makerBackground@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/makerBackground.imageset/makerBackground@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/mohaengMakers.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/mohaengMakers.imageset/mohaengMakers.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/mohaengMakers.imageset/mohaengMakers@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/mohaengMakers.imageset/mohaengMakers@3x.png
  Mohaeng/Mohaeng/Resources/Colors.xcassets/DarkYellow.colorset/Contents.json
  Mohaeng/Mohaeng/Resources/Constants/Storyboard.swift
  Mohaeng/Mohaeng/Resources/Constants/ViewController.swift
  Mohaeng/Mohaeng/Resources/Storyboards/Home/Makers.storyboard
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/MakersViewController.swift
Labels: feat 🌹, seungchan🗻

#510 [#508] 2차 QA 수정
  Mohaeng/Mohaeng/Resources/Assets.xcassets/sosoImage.imageset/sosoImage.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/sosoImage.imageset/sosoImage@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/sosoImage.imageset/sosoImage@3x.png
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/EmailLogin.storyboard
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/Login.storyboard
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/SignUpFirst.storyboard
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/SignUpThird.storyboard
  Mohaeng/Mohaeng/Resources/Storyboards/Feed/Mood.storyboard
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpFirstViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/MoodViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Reward/CuriosityRewardViewController.swift
Labels: fix 🚨, seungchan🗻

#514 [#512] 마이페이지 캘린더 터치되는 현상 수정
  Mohaeng/Mohaeng/Resources/Storyboards/Home/MyPage.storyboard
Labels: fix 🚨, choyi 🎱

#519 [#516] 2차 QA 반영
  Mohaeng/Mohaeng.xcodeproj/project.pbxproj
  Mohaeng/Mohaeng/Resources/Storyboards/Home/Home.storyboard
  Mohaeng/Mohaeng/Sources/AppModels/HomeMent.swift
  Mohaeng/Mohaeng/Sources/AppModels/Ments.swift
  Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/FeedCollectionViewCell.swift
  Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/FeedCollectionViewCell.xib
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/MyDrawerViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/CharacterStyleViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/HomeViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/PopUp/HomeHappy/HappyPopUpViewController.swift
Labels: fix 🚨, yezi✨

#521 [#520] userDefault 없어서 에러나는 현상 해결
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/HomeViewController.swift
Labels: fix 🚨, yezi✨

#522 [#429] 2차 QA수정
  Mohaeng/.swiftlint.yml
  Mohaeng/Mohaeng.xcodeproj/project.pbxproj
  Mohaeng/Mohaeng/Resources/Assets.xcassets/badgeBf1.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/badgeBf1.imageset/badgeBf1.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/badgeBf1.imageset/badgeBf1@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/badgeBf1.imageset/badgeBf1@3x.png
  Mohaeng/Mohaeng/Resources/Constants/Image.swift
  Mohaeng/Mohaeng/Resources/Lottie/RewardCards/awards_sok7.json
  Mohaeng/Mohaeng/Resources/Lottie/awards_congrats.json
  Mohaeng/Mohaeng/Resources/Lottie/letter.json
  Mohaeng/Mohaeng/Sources/APIModels/Badge.swift
  Mohaeng/Mohaeng/Sources/AppModels/Reward.swift
  Mohaeng/Mohaeng/Sources/Cells/BadgeCollectionView/BadgeCollectionViewCell.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/WritingViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/Badge/BadgeModalViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/Badge/BadgeViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/OnBoarding/OnBoarding2ViewController.swift
  Mohaeng/Mohaeng/Sources/Views/OnBoarding/OnBoardingChallengeCardView.swift
Labels: fix 🚨, yoonseo 🥑

#524 [#517] 약관동의 폰트 수정 & 네비게이션바 백버튼 추가
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/SignUpSecond.storyboard
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpSecondViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpThirdViewController.swift
Labels: fix 🚨, seungchan🗻

#525 [#515] 환경설정 뷰, 통신
  Mohaeng/Mohaeng.xcodeproj/project.pbxproj
  Mohaeng/Mohaeng/Resources/Constants/Storyboard.swift
  Mohaeng/Mohaeng/Resources/Constants/String.swift
  Mohaeng/Mohaeng/Resources/Constants/URL.swift
  Mohaeng/Mohaeng/Resources/Constants/ViewController.swift
  Mohaeng/Mohaeng/Resources/Storyboards/Home/Makers.storyboard
  Mohaeng/Mohaeng/Resources/Storyboards/Home/OpenSourceLicense.storyboard
  Mohaeng/Mohaeng/Resources/Storyboards/Home/Setting.storyboard
  Mohaeng/Mohaeng/Sources/APIServices/AuthAPI/SignUpAPI.swift
  Mohaeng/Mohaeng/Sources/APIServices/AuthAPI/SignUpService.swift
  Mohaeng/Mohaeng/Sources/Cells/SettingTableViewCell.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/HomeViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/Setting/OpenSourceLicenseViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/Setting/SettingViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/SettingViewController.swift
  README.md
Labels: feat 🌹, choyi 🎱

#539 [#537] 닉네임 UserDefaults
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpThirdViewController.swift
Labels: fix 🚨, seungchan🗻

#530 [#528] 3차 QA 수정 사항
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/Login.storyboard
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/MyDrawerViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/CharacterStyleViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/HomeViewController.swift
Labels: fix 🚨, yezi✨

#535 [#532] 기분선택 이미지 수정
  Mohaeng/Mohaeng/Resources/Assets.xcassets/badImage.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/badImage.imageset/badImage @2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/badImage.imageset/badImage @3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/badImage.imageset/badImage.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/badImage.imageset/badImage@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/badImage.imageset/badImage@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/happyImage.imageset/happyImage.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/happyImage.imageset/happyImage@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/happyImage.imageset/happyImage@3x.png
Labels: fix 🚨, seungchan🗻

#540 [#538] Reward flow 에 isPanalty 반영
  Mohaeng/Mohaeng/Sources/ViewControllers/Reward/ChallengeRewardViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Reward/CourseRewardViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Reward/LevelUpRewardViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Reward/WritingRewardViewController.swift
Labels: fix 🚨, yoonseo 🥑

#543 [#531] 3차 QA 반영
  Mohaeng/Mohaeng/Sources/Cells/CourseLibraryCollectionVIew/CourseLibraryCollectionViewCell.xib
  Mohaeng/Mohaeng/Sources/Cells/NotificationCollectionView/ProfileBubbleCollectionViewCell.xib
Labels: fix 🚨, choyi 🎱

#547 [#531] 3차 QA 반영
  Mohaeng/Mohaeng/Sources/Cells/NotificationCollectionView/BubbleCollectionViewCell.xib
  Mohaeng/Mohaeng/Sources/Cells/NotificationCollectionView/ProfileBubbleCollectionViewCell.xib
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/Mypage/MyPageViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/NotificationViewController.swift
Labels: fix 🚨, choyi 🎱

#545 [#544] 서버 변경사항 적용
  Mohaeng/Mohaeng/Sources/APIModels/CourseHistory.swift
  Mohaeng/Mohaeng/Sources/APIServices/ChallengeAPI/ChallengeService.swift
Labels: fix 🚨, choyi 🎱

#549 [#548] 인덱스 에러 수정
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/CharacterStyleViewController.swift
Labels: fix 🚨, yezi✨

#551 [#550] 메인 멘트 로드 시점 변경
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/HomeViewController.swift
Labels: fix 🚨, yezi✨

#553 [#542] mailTo 함수 추가
  Mohaeng/Mohaeng/Resources/Storyboards/Challenge/Course.storyboard
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/Setting/SettingViewController.swift
Labels: feat 🌹, choyi 🎱

#554 [#541] Tabbar background iOS15 대응
  Mohaeng/Mohaeng/Resources/Storyboards/Tabbar.storyboard
  Mohaeng/Mohaeng/Sources/ViewControllers/TabbarViewController.swift
Labels: fix 🚨, choyi 🎱

#555 [#367] 기존 NavigationController Extension 삭제
  Mohaeng/Mohaeng/Sources/Extensions/UINavigationController+Extension.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/OnBoarding/OnBoarding1ViewController.swift
Labels: fix 🚨, choyi 🎱

#559 [#556] iOS 14 이하에서 코스 라이브러리 property collectionView 중복 선택되는 이슈 해결
  Mohaeng/Mohaeng/Sources/Cells/CourseLibraryCollectionVIew/CourseCategoryCollectionViewCell.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
Labels: fix 🚨, choyi 🎱

#561 [#550] 메인뷰 로티 레이아웃 수정
  Mohaeng/Mohaeng/Resources/Storyboards/Home/Home.storyboard
Labels: fix 🚨, yezi✨

#552 [#536] 3차 QA 수정
  Mohaeng/Mohaeng/Resources/Assets.xcassets/appleIcon.imageset/appleIcon.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/appleIcon.imageset/appleIcon@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/appleIcon.imageset/appleIcon@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/btnStartApple.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/btnStartApple.imageset/btnStartApple.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/btnStartApple.imageset/btnStartApple@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/btnStartApple.imageset/btnStartApple@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/btnStartEmail.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/btnStartEmail.imageset/btnStartEmail.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/btnStartEmail.imageset/btnStartEmail@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/btnStartEmail.imageset/btnStartEmail@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/btnStartKakao.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/btnStartKakao.imageset/btnStartKakao.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/btnStartKakao.imageset/btnStartKakao@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/btnStartKakao.imageset/btnStartKakao@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/grpXNickName.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/grpXNickName.imageset/grpXNickName.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/grpXNickName.imageset/grpXNickName@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/grpXNickName.imageset/grpXNickName@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/kakaoIcon.imageset/kakaoIcon.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/kakaoIcon.imageset/kakaoIcon@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/kakaoIcon.imageset/kakaoIcon@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/nickNameImage.imageset/nickNameImage.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/nickNameImage.imageset/nickNameImage@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/nickNameImage.imageset/nickNameImage@3x.png
  Mohaeng/Mohaeng/Resources/Colors.xcassets/DarkGrey.colorset/Contents.json
  Mohaeng/Mohaeng/Resources/Constants/URL.swift
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/Login.storyboard
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/SignUpFirst.storyboard
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/SignUpSecond.storyboard
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/SignUpThird.storyboard
  Mohaeng/Mohaeng/Sources/APIModels/Auth.swift
  Mohaeng/Mohaeng/Sources/APIServices/AuthAPI/SignUpAPI.swift
  Mohaeng/Mohaeng/Sources/APIServices/AuthAPI/SignUpService.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/LoginViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpFirstViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpThirdViewController.swift
Labels: fix 🚨, seungchan🗻

#562 [#557] 채팅 뷰 cell truncation, height 이슈 해결
  Mohaeng/Mohaeng.xcodeproj/project.pbxproj
  Mohaeng/Mohaeng/Sources/Cells/NotificationCollectionView/BubbleCollectionViewCell.xib
  Mohaeng/Mohaeng/Sources/Cells/NotificationCollectionView/ProfileBubbleCollectionViewCell.xib
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/NotificationViewController.swift
Labels: fix 🚨, choyi 🎱

#566 [#563] 약관 동의 수정
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/SignUpSecond.storyboard
Labels: fix 🚨, seungchan🗻

#565 [#564] SignUpApi 머지 이슈
  Mohaeng/Mohaeng/Sources/APIServices/AuthAPI/SignUpService.swift
Labels: fix 🚨, seungchan🗻

#567 [#558] WritingVC header client 추가
  Mohaeng/Mohaeng/Sources/APIServices/FeedAPI/FeedService.swift
Labels: fix 🚨, yoonseo 🥑

#569 [#568] 피드 멘트 변경
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedViewController.swift
Labels: chore 🛠, yezi✨

#575 [#571] 홈뷰 네비바 아이콘 변경
  Mohaeng/Mohaeng/Resources/Assets.xcassets/gnbIcnMedal.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/gnbIcnMedal.imageset/gnbIcnMedal.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/gnbIcnMedal.imageset/gnbIcnMedal@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/gnbIcnMedal.imageset/gnbIcnMedal@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/gnbIcnMypage.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/gnbIcnMypage.imageset/gnbIcnMypage.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/gnbIcnMypage.imageset/gnbIcnMypage@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/gnbIcnMypage.imageset/gnbIcnMypage@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/gnbIcnNotice.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/gnbIcnNotice.imageset/gnbIcnNotice.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/gnbIcnNotice.imageset/gnbIcnNotice@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/gnbIcnNotice.imageset/gnbIcnNotice@3x.png
  Mohaeng/Mohaeng/Resources/Constants/Image.swift
Labels: feat 🌹, yezi✨

#576 [#572] 챌린지 기록보기 empty 뷰 추가
  Mohaeng/Mohaeng/Resources/Storyboards/Home/CourseHistory.storyboard
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/Mypage/CourseHistoryViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/NotificationViewController.swift
Labels: feat 🌹, choyi 🎱

#577 [#573] pop했을 때 calendar 색 사라지는 이슈 해결
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/Mypage/MyPageViewController.swift
Labels: fix 🚨, choyi 🎱

#574 [#570] 로그인 버튼 살리기
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpFirstViewController.swift
Labels: fix 🚨, seungchan🗻

#578 [#NON_ISSUE] README 사진 변경
  README.md
Labels: chore 🛠, choyi 🎱

#580 [#579] 오타 수정
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedViewController.swift
Labels: fix 🚨, style 👗, yezi✨

#584 [#583] 비밀번호찾기 특수문자 포함 검사 추가
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/FindPasswordViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/NewPasswordViewController.swift
Labels: fix 🚨, choyi 🎱

#585 [NON_ISSUE] 챌린지 뷰 높이 수정
  Mohaeng/Mohaeng/Sources/Views/ChallengeStampView.xib
Labels: fix 🚨, choyi 🎱

#582 [#581] 닉네임 수정에서 이메일 특수문자 에러 해결
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpFirstViewController.swift
Labels: fix 🚨, seungchan🗻

#587 [#586] 애플, 카카오 이미지 수정
  Mohaeng/Mohaeng/Resources/Assets.xcassets/appleLogin.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/appleLogin.imageset/appleLogin.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/appleLogin.imageset/appleLogin@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/appleLogin.imageset/appleLogin@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/btnStartApple.imageset/btnStartApple.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/btnStartApple.imageset/btnStartApple@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/btnStartApple.imageset/btnStartApple@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/btnStartKakao.imageset/btnStartKakao.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/btnStartKakao.imageset/btnStartKakao@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/btnStartKakao.imageset/btnStartKakao@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/kakaoLogin.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/kakaoLogin.imageset/kakaoLogin.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/kakaoLogin.imageset/kakaoLogin@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/kakaoLogin.imageset/kakaoLogin@3x.png
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/Login.storyboard
Labels: fix 🚨, seungchan🗻

#589 [#588] Reward 이슈 수정
  Mohaeng/Mohaeng/Sources/ViewControllers/Reward/CourseRewardViewController.swift
Labels: yoonseo 🥑

#591 [#590] 기기 대응 및 스티커 레이아웃 수정
  Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/FeedDetailCollectionViewCell.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedDetailViewController.swift
Labels: fix 🚨, yezi✨

#594 [#592] Reward, Feed 버그 수정
  Mohaeng/Mohaeng/Sources/AppModels/Reward.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedDetailViewController.swift
Labels: fix 🚨

#596 [#593] 비밀번호 8,12 로 수정
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/NewPassword.storyboard
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/NewPasswordViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpFirstViewController.swift
Labels: fix 🚨, seungchan🗻

#597 [#595] 아이패드 타겟 제거
  Mohaeng/Mohaeng.xcodeproj/project.pbxproj
Labels: fix 🚨, yezi✨

#599 [#598] 챌린지뷰 네비바 고정, section header 날짜 연결
  Mohaeng/Mohaeng/Resources/Storyboards/Challenge/Course.storyboard
  Mohaeng/Mohaeng/Sources/ViewControllers/Challenge/CourseViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/OnBoarding/OnBoarding3ViewController.swift
  Mohaeng/Mohaeng/Sources/Views/CourseHeaderView.swift
  Mohaeng/Mohaeng/Sources/Views/CourseHeaderView.xib
Labels: fix 🚨, choyi 🎱

#602 [#600, #601] 가로모드 제한 및 팝업 present 방식 변경
  Mohaeng/Mohaeng/Sources/AppDelegate.swift
  Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/FeedDetailCollectionViewCell.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedDetailViewController.swift
Labels: fix 🚨, yezi✨

#603 [#601] delete post Id
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedDetailViewController.swift
Labels: fix 🚨, yezi✨

#605 #601: 신고 버튼 선택 시 경고 alert
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedDetailViewController.swift
Labels: feat 🌹, yezi✨

#607 [#606] EULA
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/SignUpSecond.storyboard
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/AgreeViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpSecondViewController.swift
Labels: feat 🌹, seungchan🗻

#609 [#608] bug fix
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedDetailViewController.swift
Labels: fix 🚨, yezi✨

#613 [#612] 사용자 블락 로직 추가
  Mohaeng/Mohaeng/Resources/Constants/URL.swift
  Mohaeng/Mohaeng/Sources/APIServices/FeedAPI/FeedAPI.swift
  Mohaeng/Mohaeng/Sources/APIServices/FeedAPI/FeedService.swift
  Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/FeedDetailCollectionViewCell.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedDetailViewController.swift
Labels: feat 🌹, yezi✨
