Repository team-mohaeng/mohaeng-iOS, pull requests merged in 2021-09, with the labels that each got.

#300 [#280] HomeAPI - 서버 통신 Response 값 GenericResponse로 리팩토링
  Journey/Journey/Sources/APIModels/Home.swift
  Journey/Journey/Sources/APIServices/HomeAPI/HomeAPI.swift
Labels: refactor 🥲, choyi 🎱

#299 [#296] Notification 뷰
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Assets.xcassets/textBalloonGraphic.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/textBalloonGraphic.imageset/textBalloonGraphic.png
  Journey/Journey/Resources/Assets.xcassets/textBalloonGraphic.imageset/textBalloonGraphic@2x.png
  Journey/Journey/Resources/Assets.xcassets/textBalloonGraphic.imageset/textBalloonGraphic@3x.png
  Journey/Journey/Resources/Colors.xcassets/BlackText.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/GreyTextPush2.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/YellowBg1.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/YellowIcon.colorset/Contents.json
  Journey/Journey/Resources/Constants/Storyboard.swift
  Journey/Journey/Resources/Constants/ViewController.swift
  Journey/Journey/Resources/Constants/Xib.swift
  Journey/Journey/Resources/Storyboards/Challenge/Challenge.storyboard
  Journey/Journey/Resources/Storyboards/Home/Notification.storyboard
  Journey/Journey/Sources/APIModels/PushNoti.swift
  Journey/Journey/Sources/Cells/NotificationCollectionView/BubbleCollectionViewCell.swift
  Journey/Journey/Sources/Cells/NotificationCollectionView/BubbleCollectionViewCell.xib
  Journey/Journey/Sources/Cells/NotificationCollectionView/NewNotificationCollectionReusableView.swift
  Journey/Journey/Sources/Cells/NotificationCollectionView/NewNotificationCollectionReusableView.xib
  Journey/Journey/Sources/Cells/NotificationCollectionView/ProfileBubbleCollectionViewCell.swift
  Journey/Journey/Sources/Cells/NotificationCollectionView/ProfileBubbleCollectionViewCell.xib
  Journey/Journey/Sources/Extensions/UIColor+Extension.swift
  Journey/Journey/Sources/ViewControllers/Home/NotificationViewController.swift
  Journey/Journey/Sources/Views/UnreadNotificationHeaderView.swift
  Journey/Journey/Sources/Views/UnreadNotificationHeaderView.xib
Labels: feat 🌹, choyi 🎱

#306 [#298] 피드뷰 리디자인
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Assets.xcassets/feedGrpX.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/feedGrpX.imageset/feedGrpX.png
  Journey/Journey/Resources/Assets.xcassets/feedGrpX.imageset/feedGrpX@2x.png
  Journey/Journey/Resources/Assets.xcassets/feedGrpX.imageset/feedGrpX@3x.png
  Journey/Journey/Resources/Assets.xcassets/feedHandGrpX.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/feedHandGrpX.imageset/feedHandGrpX.png
  Journey/Journey/Resources/Assets.xcassets/feedHandGrpX.imageset/feedHandGrpX@2x.png
  Journey/Journey/Resources/Assets.xcassets/feedHandGrpX.imageset/feedHandGrpX@3x.png
  Journey/Journey/Resources/Assets.xcassets/feednoneGrp.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/feednoneGrp.imageset/feednoneGrp.png
  Journey/Journey/Resources/Assets.xcassets/feednoneGrp.imageset/feednoneGrp@2x.png
  Journey/Journey/Resources/Assets.xcassets/feednoneGrp.imageset/feednoneGrp@3x.png
  Journey/Journey/Resources/Assets.xcassets/gnbIcnWrite.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/gnbIcnWrite.imageset/gnbIcnWrite.png
  Journey/Journey/Resources/Assets.xcassets/gnbIcnWrite.imageset/gnbIcnWrite@2x.png
  Journey/Journey/Resources/Assets.xcassets/gnbIcnWrite.imageset/gnbIcnWrite@3x.png
  Journey/Journey/Resources/Constants/Image.swift
  Journey/Journey/Resources/Constants/Xib.swift
  Journey/Journey/Resources/Storyboards/Feed/Feed.storyboard
  Journey/Journey/Sources/APIModels/Community.swift
  Journey/Journey/Sources/APIModels/Feed.swift
  Journey/Journey/Sources/APIModels/FeedDetail.swift
  Journey/Journey/Sources/APIModels/MyDrawer.swift
  Journey/Journey/Sources/APIServices/FeedAPI/FeedAPI.swift
  Journey/Journey/Sources/Cells/FeedCollectionView/ContentsCollectionViewCell.swift
  Journey/Journey/Sources/Cells/FeedCollectionView/FeedCollectionViewCell.swift
  Journey/Journey/Sources/Cells/FeedCollectionView/FeedCollectionViewCell.xib
  Journey/Journey/Sources/ViewControllers/Feed/FeedDetailViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/MyDrawerViewController.swift
  Journey/Journey/Sources/Views/FeedHeaderView.swift
  Journey/Journey/Sources/Views/FeedHeaderView.xib
Labels: feat 🌹, yezi✨

#311 [#298] HeaderView Const 추가
  Journey/Journey/Resources/Constants/Xib.swift
Labels: chore 🛠, yezi✨

#315 [#314] 무채색계열 컬러 에셋 추가하기
  Journey/Journey/Resources/Colors.xcassets/Mohaeng-Fix/Black.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Mohaeng-Fix/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Mohaeng-Fix/Grey1.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Mohaeng-Fix/Grey2.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Mohaeng-Fix/Grey3.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Mohaeng-Fix/Grey4.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Mohaeng-Fix/Grey5.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Mohaeng-Fix/GreyButton1.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Mohaeng-Fix/GreyButton2.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Mohaeng-Fix/GreyIconGnb.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Mohaeng-Fix/GreyIconNavi.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Mohaeng-Fix/GreyTextNavi.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Mohaeng-Fix/White.colorset/Contents.json
  Journey/Journey/Sources/Extensions/UIColor+Extension.swift
Labels: chore 🛠, choyi 🎱

#313 [#304] 인증번호 입력 뷰 변경사항 적용
  Journey/Journey/Resources/Storyboards/Auth/Code.storyboard
  Journey/Journey/Sources/ViewControllers/Auth/CodeViewController.swift
Labels: feat 🌹, choyi 🎱

#307 [#305] 이메일로 로그인
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Colors.xcassets/Black1Text.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/DeepYellow.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Grey2Text.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/Grey5.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/LoginYellow.colorset/Contents.json
  Journey/Journey/Resources/Constants/Storyboard.swift
  Journey/Journey/Resources/Constants/ViewController.swift
  Journey/Journey/Resources/Storyboards/Auth/EmailLogin.storyboard
  Journey/Journey/Resources/Storyboards/Auth/Login.storyboard
  Journey/Journey/Sources/Extensions/UIColor+Extension.swift
  Journey/Journey/Sources/ViewControllers/Auth/EmailLoginViewController.swift
  Journey/Journey/Sources/ViewControllers/Auth/LoginViewController.swift
  Journey/Podfile.lock
Labels: feat 🌹, seungchan🗻

#312 [#308] 이메일로 회원가입
  Journey/Journey/Resources/Assets.xcassets/yellowCheck.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/yellowCheck.imageset/yelloCheck@2x.png
  Journey/Journey/Resources/Assets.xcassets/yellowCheck.imageset/yellowCheck.png
  Journey/Journey/Resources/Assets.xcassets/yellowCheck.imageset/yellowCheck@3x.png
  Journey/Journey/Resources/Colors.xcassets/Journey/DeepYellow.colorset/Contents.json
  Journey/Journey/Resources/Storyboards/Auth/SignUpFirst.storyboard
  Journey/Journey/Sources/ViewControllers/Auth/SignUpFirstViewController.swift
Labels: feat 🌹, seungchan🗻

#316 [#310] 내 서랍장 리디자인
  Journey/Journey/Resources/Colors.xcassets/YellowText1.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/todayYellow.colorset/Contents.json
  Journey/Journey/Resources/Storyboards/Feed/MyDrawer.storyboard
  Journey/Journey/Sources/Cells/FeedCollectionView/FeedCollectionViewCell.swift
  Journey/Journey/Sources/Cells/FeedCollectionView/FeedCollectionViewCell.xib
  Journey/Journey/Sources/Extensions/ModalPresentationController.swift
  Journey/Journey/Sources/Extensions/UIColor+Extension.swift
  Journey/Journey/Sources/ViewControllers/Feed/FeedViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/MyDrawerViewController.swift
  Journey/Journey/Sources/Views/DatePickerViewController.swift
  Journey/Journey/Sources/Views/DatePickerViewController.xib
  Journey/Journey/Sources/Views/FeedHeaderView.swift
  Journey/Journey/Sources/Views/FeedHeaderView.xib
  Journey/Journey/Sources/Views/MyDrawerCollectionReusableView.xib
Labels: feat 🌹, yezi✨

#302 [#301] 비밀번호 찾기 뷰 변경사항 적용
  Journey/Journey/Resources/Storyboards/Auth/FindPassword.storyboard
  Journey/Journey/Sources/ViewControllers/Auth/FindPasswordViewController.swift
Labels: feat 🌹, choyi 🎱

#322 [#321] CourseLibrary 뷰 리디자인
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey.xcodeproj/xcshareddata/xcschemes/Journey.xcscheme
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/BlueThemeBubble.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/BlueThemeDark.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/BlueThemeLight.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/GreenThemeBubble.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/GreenThemeDark.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/GreenThemeLight.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/IndigoThemeBubble.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/IndigoThemeDark.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/IndigoThemeLight.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/OrangeThemeBubble.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/OrangeThemeDark.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/OrangeThemeLight.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/PurpleThemeBubble.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/PurpleThemeDark.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/PurpleThemeLight.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/RedThemeBubble.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/RedThemeDark.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/RedThemeLight.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/YellowThemeBubble.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/YellowThemeDark.colorset/Contents.json
  Journey/Journey/Resources/Colors.xcassets/sampleThemeColor/YellowThemeLight.colorset/Contents.json
  Journey/Journey/Resources/Constants/Xib.swift
  Journey/Journey/Resources/Storyboards/Challenge/CourseLibrary.storyboard
  Journey/Journey/Sources/APIModels/CourseLibrary.swift
  Journey/Journey/Sources/AppModels/AppCourse.swift
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/CourseCategoryCollectionViewCell.swift
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/CourseLibraryCollectionViewCell.swift
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/CourseLibraryCollectionViewCell.xib
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/DoneCourseCollectionViewCell.xib
  Journey/Journey/Sources/Cells/CourseLibraryCollectionVIew/UndoneCourseCollectionViewCell.swift
  Journey/Journey/Sources/Extensions/UIColor+Extension.swift
  Journey/Journey/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
  Journey/Journey/Sources/ViewModels/CourseListViewModel.swift
Labels: feat 🌹, choyi 🎱

#328 [#303] home navigation item 클릭 시 터지는 문제 해결
  Mohaeng/Mohaeng/Sources/Extensions/UINavigationItem+Extensions.swift
Labels: fix 🚨, yezi✨

#332 [#323] 배지뷰, 배지 모달뷰 디자인
  Mohaeng/Mohaeng.xcodeproj/project.pbxproj
  Mohaeng/Mohaeng/Resources/Constants/ViewController.swift
  Mohaeng/Mohaeng/Resources/Constants/Xib.swift
  Mohaeng/Mohaeng/Resources/Storyboards/Home/Medal.storyboard
  Mohaeng/Mohaeng/Sources/APIModels/Medal.swift
  Mohaeng/Mohaeng/Sources/Cells/BadgeCollectionView/BadgeCollectionViewCell.swift
  Mohaeng/Mohaeng/Sources/Cells/MedalCollectionView/MedalCollectionViewCell.swift
  Mohaeng/Mohaeng/Sources/Cells/MedalCollectionView/MedalCollectionViewCell.xib
  Mohaeng/Mohaeng/Sources/Extensions/UIFont+Extension.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/Badge/BadgeModalViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/Badge/BadgeViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/HomeViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/MedalViewController.swift
  Mohaeng/Mohaeng/Sources/Views/MedalCollectionReusableView.swift
  Mohaeng/Mohaeng/Sources/Views/MedalCollectionReusableView.xib
Labels: feat 🌹, fix 🚨, style 👗, yoonseo 🥑

#338 [#337] 코스 라이브러리 뷰 코스 별 filter
  Mohaeng/Mohaeng/Resources/Storyboards/Challenge/CourseLibrary.storyboard
  Mohaeng/Mohaeng/Sources/ViewControllers/Challenge/CourseLibraryViewController.swift
  Mohaeng/Mohaeng/Sources/ViewModels/CourseListViewModel.swift
Labels: feat 🌹, choyi 🎱

#335 [#317] 피드 디테일뷰 리디자인
  Mohaeng/Mohaeng.xcodeproj/project.pbxproj
  Mohaeng/Mohaeng/Resources/Assets.xcassets/img.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/img.imageset/img.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/img.imageset/img@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/img.imageset/img@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/mood.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/mood.imageset/mood.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/mood.imageset/mood@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/mood.imageset/mood@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/plusTch.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/plusTch.imageset/plusTch.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/plusTch.imageset/plusTch@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/plusTch.imageset/plusTch@3x.png
  Mohaeng/Mohaeng/Resources/Constants/Xib.swift
  Mohaeng/Mohaeng/Resources/Storyboards/Feed/FeedDetail.storyboard
  Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/FeedContentsCollectionViewCell.swift
  Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/FeedContentsCollectionViewCell.xib
  Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/FeedDetailCollectionViewCell.swift
  Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/PlusButtonCollectionViewCell.swift
  Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/PlusButtonCollectionViewCell.xib
  Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/StickerCollectionViewCell.swift
  Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/StickerCollectionViewCell.xib
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedDetailViewController.swift
Labels: feat 🌹, yezi✨

#330 [#320] 피드 기분 선택 뷰
  Mohaeng/Mohaeng.xcodeproj/project.pbxproj
  Mohaeng/Mohaeng/Resources/Assets.xcassets/badImage.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/badImage.imageset/badImage @2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/badImage.imageset/badImage @3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/badImage.imageset/badImage.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/happyImage.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/happyImage.imageset/happyImage.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/happyImage.imageset/happyImage@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/happyImage.imageset/happyImage@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/rightBackButton.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/rightBackButton.imageset/rightBackButton.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/rightBackButton.imageset/rightBackButton@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/rightBackButton.imageset/rightBackButton@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/sosoImage.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/sosoImage.imageset/sosoImage.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/sosoImage.imageset/sosoImage@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/sosoImage.imageset/sosoImage@3x.png
  Mohaeng/Mohaeng/Resources/Constants/Image.swift
  Mohaeng/Mohaeng/Resources/Constants/Xib.swift
  Mohaeng/Mohaeng/Resources/Storyboards/Feed/Mood.storyboard
  Mohaeng/Mohaeng/Sources/Cells/FeedView/MoodCollectionViewCell.swift
  Mohaeng/Mohaeng/Sources/Cells/FeedView/MoodCollectionViewCell.xib
  Mohaeng/Mohaeng/Sources/Extensions/MoodViewController+Carousel.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/MoodViewController.swift
  Mohaeng/Mohaeng/Sources/Views/CarouselLayoutView.swift
Labels: feat 🌹, seungchan🗻
