Repository team-mohaeng/mohaeng-iOS, pull requests merged in 2021-08, with the labels that each got.

#283 [#281] base url 변경
  Journey/Journey/Resources/Constants/URL.swift
Labels: chore 🛠

#282 [#278] 서버 통신 Response 값 GenericResponse로 리팩토링
  Journey/Journey/Sources/APIModels/Auth.swift
  Journey/Journey/Sources/APIModels/Course.swift
  Journey/Journey/Sources/APIModels/Medal.swift
  Journey/Journey/Sources/APIServices/AuthAPI/LoginAPI.swift
  Journey/Journey/Sources/APIServices/AuthAPI/PasswordAPI.swift
  Journey/Journey/Sources/APIServices/AuthAPI/SignUpAPI.swift
  Journey/Journey/Sources/APIServices/ChallengeAPI/ChallengeAPI.swift
  Journey/Journey/Sources/APIServices/CourseAPI/CourseAPI.swift
  Journey/Journey/Sources/Extensions/UIColor+Extension.swift
Labels: refactor 🥲, choyi 🎱

#288 [#287] FontBlaster 도입, G마켓 Sans 폰트 추가
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Font/GmarketSansTTFBold.ttf
  Journey/Journey/Resources/Font/GmarketSansTTFLight.ttf
  Journey/Journey/Resources/Font/GmarketSansTTFMedium.ttf
  Journey/Journey/Sources/AppDelegate.swift
  Journey/Podfile
  Journey/Podfile.lock
Labels: chore 🛠, choyi 🎱

#289 [#286] 챌린지 뷰 리디자인 - header view
  Journey/Journey.xcodeproj/project.pbxproj
  Journey/Journey/Resources/Assets.xcassets/challengeHelpButton.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/challengeHelpButton.imageset/challengeHelpButton.png
  Journey/Journey/Resources/Assets.xcassets/challengeHelpButton.imageset/challengeHelpButton@2x.png
  Journey/Journey/Resources/Assets.xcassets/challengeHelpButton.imageset/challengeHelpButton@3x.png
  Journey/Journey/Resources/Assets.xcassets/sampleChallengeRacoon.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/sampleChallengeRacoon.imageset/sampleChallengeRacoon.png
  Journey/Journey/Resources/Assets.xcassets/sampleChallengeRacoon.imageset/sampleChallengeRacoon@2x.png
  Journey/Journey/Resources/Assets.xcassets/sampleChallengeRacoon.imageset/sampleChallengeRacoon@3x.png
  Journey/Journey/Resources/Assets.xcassets/scrollDownIcn.imageset/Contents.json
  Journey/Journey/Resources/Assets.xcassets/scrollDownIcn.imageset/scrollDownIcn.png
  Journey/Journey/Resources/Assets.xcassets/scrollDownIcn.imageset/scrollDownIcn@2x.png
  Journey/Journey/Resources/Assets.xcassets/scrollDownIcn.imageset/scrollDownIcn@3x.png
  Journey/Journey/Resources/Constants/Xib.swift
  Journey/Journey/Resources/Storyboards/Challenge/Course.storyboard
  Journey/Journey/Sources/ViewControllers/Challenge/CourseViewController.swift
  Journey/Journey/Sources/Views/ChallengeStampView.swift
  Journey/Journey/Sources/Views/ChallengeStampView.xib
Labels: feat 🌹, choyi 🎱

#285 [#284] AppDate 수정
  Journey/Journey/Sources/AppModels/AppDate.swift
  Journey/Journey/Sources/ViewControllers/Feed/MoodViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/MyDrawerViewController.swift
  Journey/Journey/Sources/ViewControllers/Feed/WritingViewController.swift
  Journey/Journey/Sources/Views/DatePickerViewController.swift
  Journey/Journey/Sources/Views/MyDrawerCollectionReusableView.swift
Labels: refactor 🥲, yezi✨
