Repository team-mohaeng/mohaeng-iOS, pull requests merged in 2021-10, with the labels that each got.

#341 [#324] 마이페이지 뷰
  Mohaeng/Mohaeng.xcodeproj/project.pbxproj
  Mohaeng/Mohaeng/Resources/Assets.xcassets/chevron_left.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/chevron_left.imageset/chevron_left.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/chevron_left.imageset/chevron_left@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/chevron_left.imageset/chevron_left@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/chevron_right.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/chevron_right.imageset/chevron_right.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/chevron_right.imageset/chevron_right@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/chevron_right.imageset/chevron_right@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/editTch.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/editTch.imageset/editTch.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/editTch.imageset/editTch@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/editTch.imageset/editTch@3x.png
  Mohaeng/Mohaeng/Resources/Colors.xcassets/Mohaeng-Fix/Yellow6.colorset/Contents.json
  Mohaeng/Mohaeng/Resources/Colors.xcassets/Mohaeng-Fix/Yellow7.colorset/Contents.json
  Mohaeng/Mohaeng/Resources/Constants/Storyboard.swift
  Mohaeng/Mohaeng/Resources/Constants/ViewController.swift
  Mohaeng/Mohaeng/Resources/Constants/Xib.swift
  Mohaeng/Mohaeng/Resources/Storyboards/Home/MyPage.storyboard
  Mohaeng/Mohaeng/Sources/APIModels/MyPage.swift
  Mohaeng/Mohaeng/Sources/Cells/MyPageCalendar/DateCollectionViewCell.swift
  Mohaeng/Mohaeng/Sources/Extensions/UIView+Extension.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/MyPageViewController.swift
  Mohaeng/Podfile
  Mohaeng/Podfile.lock
Labels: feat 🌹, choyi 🎱

#352 [#351] addShadowWithOpaqueBackground() 자료형 이슈
  Mohaeng/Mohaeng/Sources/Extensions/UIView+Extension.swift
Labels: fix 🚨, choyi 🎱

#350 [#346] 뷰 트랜지션 점검
  Mohaeng/Mohaeng/Resources/Colors.xcassets/Mohaeng-Fix/YellowIconNavi.colorset/Contents.json
  Mohaeng/Mohaeng/Resources/Storyboards/Challenge/Course.storyboard
  Mohaeng/Mohaeng/Resources/Storyboards/Tabbar.storyboard
  Mohaeng/Mohaeng/Sources/Cells/CourseTableView/EvenDayTableViewCell.swift
  Mohaeng/Mohaeng/Sources/Cells/CourseTableView/FirstDayTableViewCell.swift
  Mohaeng/Mohaeng/Sources/Cells/CourseTableView/OddDayTableViewCell.swift
  Mohaeng/Mohaeng/Sources/Extensions/UIColor+Extension.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/LoginViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Challenge/CourseViewController.swift
  Mohaeng/Mohaeng/Sources/Views/CourseFooterView.swift
Labels: style 👗, choyi 🎱

#368 [#358] 피드 커뮤니티뷰 수정사항 반영
  Mohaeng/Mohaeng/Resources/Assets.xcassets/feedCha.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/feedCha.imageset/feedCha.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/feedCha.imageset/feedCha@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/feedCha.imageset/feedCha@3x.png
  Mohaeng/Mohaeng/Resources/Constants/Image.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/FeedViewController.swift
  Mohaeng/Mohaeng/Sources/Views/FeedHeaderView.swift
  Mohaeng/Mohaeng/Sources/Views/FeedHeaderView.xib
Labels: feat 🌹, refactor 🥲, yezi✨

#353 [#331] 닉네임뷰 구현
  Mohaeng/Mohaeng/Resources/Assets.xcassets/nickNameImage.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/nickNameImage.imageset/nickNameImage.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/nickNameImage.imageset/nickNameImage@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/nickNameImage.imageset/nickNameImage@3x.png
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/SignUpThird.storyboard
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpThirdViewController.swift
Labels: feat 🌹, seungchan🗻

#362 [#361] 약관동의 뷰 구현
  Mohaeng/Mohaeng/Resources/Assets.xcassets/checkButton.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/checkButton.imageset/checkButton.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/checkButton.imageset/checkButton@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/checkButton.imageset/checkButton@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/uncheckButton.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/uncheckButton.imageset/uncheckButton.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/uncheckButton.imageset/uncheckButton@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/uncheckButton.imageset/uncheckButton@3x.png
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/SignUpSecond.storyboard
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpSecondViewController.swift
Labels: feat 🌹, seungchan🗻

#396 [#388] 로그인 뷰 오토레이아웃, 폰트 수정
  Mohaeng/Mohaeng.xcodeproj/xcshareddata/xcschemes/Mohaeng.xcscheme
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/Login.storyboard
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/LoginViewController.swift
Labels: fix 🚨, seungchan🗻

#448 [#447] 해피지수 프로그래스바에 반영
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/HomeViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/PopUp/HomeHappy/HappyPopUpViewController.swift
Labels: feat 🌹, yezi✨

#465 [#419] 카카오톡 로그인 구현 및 코드 컨벤션 수정
  Mohaeng/Mohaeng.xcodeproj/project.pbxproj
  Mohaeng/Mohaeng/Resources/Constants/URL.swift
  Mohaeng/Mohaeng/Resources/Info.plist
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/Login.storyboard
  Mohaeng/Mohaeng/Sources/APIServices/AuthAPI/KakaoAPI.swift
  Mohaeng/Mohaeng/Sources/APIServices/AuthAPI/KakaoService.swift
  Mohaeng/Mohaeng/Sources/AppDelegate.swift
  Mohaeng/Mohaeng/Sources/AppModels/SignUpUser.swift
  Mohaeng/Mohaeng/Sources/SceneDelegate.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/LoginViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpFirstViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpThirdViewController.swift
  Mohaeng/Podfile
  Mohaeng/Podfile.lock
Labels: feat 🌹, choyi 🎱

#492 [#491] 기본값 점검 및 QA 사항 수정
  Mohaeng/Mohaeng/Resources/Assets.xcassets/feedPlaceholder.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/feedPlaceholder.imageset/feedPlaceholder.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/feedPlaceholder.imageset/feedPlaceholder@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/feedPlaceholder.imageset/feedPlaceholder@3x.png
  Mohaeng/Mohaeng/Resources/Constants/Image.swift
  Mohaeng/Mohaeng/Resources/Storyboards/Home/CharacterStyle.storyboard
  Mohaeng/Mohaeng/Resources/Storyboards/Home/Home.storyboard
  Mohaeng/Mohaeng/Sources/AppModels/AppDate.swift
  Mohaeng/Mohaeng/Sources/Cells/CharaterCollectionView/CharacterTypeCollectionViewCell.xib
  Mohaeng/Mohaeng/Sources/Cells/FeedCollectionView/FeedCollectionViewCell.swift
  Mohaeng/Mohaeng/Sources/Extensions/UIImageView+Extension.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Feed/MyDrawerViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/CharacterStyleViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/HomeViewController.swift
  Mohaeng/Mohaeng/Sources/Views/MyDrawerCollectionReusableView.swift
Labels: feat 🌹, yezi✨

#489 [#488] 수정된 api response 반영
  Mohaeng/Mohaeng/Resources/Storyboards/Home/CharacterStyle.storyboard
  Mohaeng/Mohaeng/Sources/APIModels/CharacterStyle.swift
  Mohaeng/Mohaeng/Sources/Cells/CharaterCollectionView/CharacterColorCollectionViewCell.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Home/CharacterStyleViewController.swift
Labels: feat 🌹, yezi✨

#482 [#460] QA 1차 수정
  Mohaeng/Mohaeng/Resources/Assets.xcassets/backgroundImage .imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/backgroundImage .imageset/backgroundImage @2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/backgroundImage .imageset/backgroundImage @3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/backgroundImage .imageset/backgroundImage.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/solemage.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/solemage.imageset/solemage.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/solemage.imageset/solemage@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/solemage.imageset/solemage@3x.png
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/EmailLogin.storyboard
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/Login.storyboard
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/SignUpFirst.storyboard
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/SignUpSecond.storyboard
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/SignUpThird.storyboard
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/EmailLoginViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/LoginViewController.swift
  Mohaeng/Mohaeng/Sources/Views/CarouselLayoutView.swift
Labels: fix 🚨, seungchan🗻

#493 [#441] 패스워드 변경 뷰, 통신
  Mohaeng/Mohaeng.xcodeproj/project.pbxproj
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/FindPassword.storyboard
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/NewPassword.storyboard
  Mohaeng/Mohaeng/Sources/APIServices/AuthAPI/PasswordService.swift
  Mohaeng/Mohaeng/Sources/SceneDelegate.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/FindPasswordViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/NewPasswordViewController.swift
Labels: feat 🌹, choyi 🎱

#496 [#494] 소셜 로그인 수정
  Mohaeng/Mohaeng.xcodeproj/project.pbxproj
  Mohaeng/Mohaeng/Resources/Constants/URL.swift
  Mohaeng/Mohaeng/Sources/APIModels/Auth.swift
  Mohaeng/Mohaeng/Sources/APIServices/AuthAPI/KakaoAPI.swift
  Mohaeng/Mohaeng/Sources/APIServices/AuthAPI/KakaoService.swift
  Mohaeng/Mohaeng/Sources/APIServices/AuthAPI/SocialAPI.swift
  Mohaeng/Mohaeng/Sources/APIServices/AuthAPI/SocialService.swift
  Mohaeng/Mohaeng/Sources/AppModels/SignUpUser.swift
  Mohaeng/Mohaeng/Sources/SceneDelegate.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/LoginViewController.swift
  Mohaeng/Mohaeng/Sources/ViewControllers/Auth/SignUpThirdViewController.swift
Labels: feat 🌹, choyi 🎱

#499 [#497] 이메일로 로그인 / 회원가입 서버 수정
  Mohaeng/Mohaeng/Sources/APIServices/AuthAPI/LoginService.swift
  Mohaeng/Mohaeng/Sources/APIServices/AuthAPI/SignUpService.swift
Labels: feat 🌹, seungchan🗻

#500 [#498] 로그인 발바닥 이미지 수정
  Mohaeng/Mohaeng/Resources/Assets.xcassets/soleImage.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/soleImage.imageset/soleImage@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/soleImage.imageset/soleImage@3x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/soleImage.imageset/soleImge.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/soleImge.imageset/Contents.json
  Mohaeng/Mohaeng/Resources/Assets.xcassets/solemage.imageset/solemage.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/solemage.imageset/solemage@2x.png
  Mohaeng/Mohaeng/Resources/Assets.xcassets/solemage.imageset/solemage@3x.png
  Mohaeng/Mohaeng/Resources/Storyboards/Auth/Login.storyboard
Labels: fix 🚨, seungchan🗻
